### PR TITLE
Fix glob patterns

### PR DESCRIPTION
**Pull request by fpoli**
There was more than one copy-paste error in the glob patterns.

### CODE REVIEW

**Comment by JonasAlaif** [comment]
Ah sorry I forgot to mention the issue with `clear_env`. The only thing you need to add is `.env("PATH", env!("PATH"))` I'd say, no need for the extra
```
.envs(&filtered_env)
.stdout(Stdio::null())
.stderr(Stdio::null())
```
(The stdout/err should only be shown if the cargo test fails anyway)

I would also say that the current glob you have is fine.

**Comment by fpoli** [comment]
I'd still like to keep `clear_env`, because it should make the test more robust in case the environment is not clean.

**Comment by JonasAlaif** [comment]
I meant using `... .env_clear().env("PATH", env!("PATH")) ...` - it's probably nicer than the `filter` and `.envs(&filtered_env)` solution. I guess the `unwrap_or_default` version also works, though it'll just fail later on anyway if PATH is not set.

**Comment by JonasAlaif** [comment]
There are also two
```
        println!(
            "Running {:?} on {:?}...",
             prusti_rustc.display(),
             program.display()
         );
```
You can replace that with ` println!("Running {:?} on {:?}...", prusti_rustc, program);` imo
Edit: I wonder if this is used elsewhere

**Comment by JonasAlaif** [comment]
I would also maybe use
```
for entry in fs::read_dir("tests/pass/").unwrap_or_else(|_| panic!("Did not find dir: {}", dir)) {
        let path = entry.unwrap().path();
```
rather than
```
let pass_entries = glob("tests/pass/**/*.rs").expect("failed to read glob pattern");
for entry in pass_entries {
```
Such that we don't need to import glob

**Comment by fpoli** [comment]
Ideally it would be nice to pipe both stderr and stdout of the child processes to stdout, but I don't see an easy way to do that. Removing the glob dependency feels a small improvement to me... I like the idea that we can easily add folders if needed.

**Comment by fpoli** [comment]
bors r+

For some reason, Windows doesn't like `env_clean()`.

**Pull request merged**
