### PR TITLE
Trait specification refinement

### PR DESCRIPTION
**Pull request by mario-bucev**
Hello,
This little PR should allow users to refine the trait specification (the refinement is obviously checked for soundness).
It is not much since one can easily emulate refinement by using Rust's shadowing system, but hey, at least it's a start :)

### CODE REVIEW

**Comment by fpoli** [comment]
Hi @mario-bucev, thank you for the PR! It looks good, but I'll properly review it as soon as I have some time, probably later this week.

Regarding the TODOs, the [Silicon](https://github.com/viperproject/silicon) Viper backend only reports one verification error per function, so that's expected. The [Carbon](https://github.com/viperproject/carbon) verifier uses a different technique and reports all verification errors, but in our experience it's not as fast as Silicon on the encoding of Rust programs.

**Comment by fpoli** [comment]
This PR looks good to me. Some errors of the method implementation may end up being reported in the contract of the trait method definition, but for this PR is acceptable that at least a verification error is reported.

I'll run some more tests in the weekend on the top 500 crates, then if they succeed the commits of this PR will automatically appear on master.

**Comment by fpoli** [comment]
The commits of this PR are now on master: 96f2627b5da307889aec72a134bb61884aa1f41f

I slightly improved the spans of the error messages. It seems to work well even with the IDE.

We handle tests and pull requests from another repository, so I have to "close" this GitHub PR even if it's accepted.

**Comment by mario-bucev** [comment]
Great, thank you for improving the error messages and doing the merge!

**Comment by fpoli** [comment]
Thank you too for proposing this! It's already available in the IDE, if you choose "install or update dependencies".

**Comment by zgrannan** [comment]
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

**Comment by zgrannan** [comment]
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

**Comment by zgrannan** [comment]
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

**Pull request closed without merging**
