### PR TITLE
Squash commits of GitHub pages

### PR DESCRIPTION
**Pull request by fpoli**
This PR adds commands that should squash the deploy commits of the GitHub pages. If approved, I'll try executing these commands manually before merging.

These commits pollute the tree and are not particularly informative:
```
> git log --graph --abbrev-commit --decorate --format=format:'%h - (%ar) - %an%d' --all
...
| * 69195ede37c - (39 minutes ago) deploy: 0ed9c6248c41f5b20a7fc98c038fcbd1f961a157 - fpoli (origin/gh-pages)
| * 4836e1040a1 - (74 minutes ago) deploy: 0ed9c6248c41f5b20a7fc98c038fcbd1f961a157 - fpoli
| * b17270e6025 - (2 days ago) deploy: a2e70818ed3cccff2349fa2d4e0b199b0a25e8e4 - Aurel300 (gh-pages)
| * 244f8291338 - (2 days ago) deploy: a2e70818ed3cccff2349fa2d4e0b199b0a25e8e4 - Aurel300
| * 1d630a8ded5 - (3 days ago) deploy: fed995e5bc2c9e63efcebc5f3bb67b7515ff7a77 - bors[bot]
| * 45d151aa7aa - (3 days ago) deploy: fed995e5bc2c9e63efcebc5f3bb67b7515ff7a77 - bors[bot]
| * c454ae20e71 - (8 days ago) deploy: 34981398a0bd12b412ce800a008aa527172013be - Aurel300
| * 02452ddaa50 - (8 days ago) deploy: 34981398a0bd12b412ce800a008aa527172013be - Aurel300
| * 794a9dd3755 - (12 days ago) deploy: 2bf067333eae186e5300bc06416024369ef44fd4 - fpoli
| * df6a295eec4 - (12 days ago) deploy: 2bf067333eae186e5300bc06416024369ef44fd4 - fpoli
| * 6a622a0c6ef - (12 days ago) deploy: ba9b3ad256f1914cbc75e60fa8a8942dc202cb23 - fpoli
| * 3438989be45 - (12 days ago) deploy: ba9b3ad256f1914cbc75e60fa8a8942dc202cb23 - fpoli
| * c322b2ea7ab - (2 weeks ago) deploy: 701759f80d1aad47bbbf29b3e88c48eb4b20fa1f - fpoli
| * 93e3017647a - (2 weeks ago) deploy: 701759f80d1aad47bbbf29b3e88c48eb4b20fa1f - fpoli
| * 225e2e09518 - (2 weeks ago) deploy: ee91e7772e764c910b1e6638f609ad5da0a791a7 - fpoli
| * 027d3028ce2 - (2 weeks ago) deploy: ee91e7772e764c910b1e6638f609ad5da0a791a7 - fpoli
| * 2b29c3c2ba5 - (2 weeks ago) deploy: ca118f6e8c76570f476b2b88b8d7527c12ba3241 - Aurel300
| * 3b21ebf4c2e - (2 weeks ago) deploy: ca118f6e8c76570f476b2b88b8d7527c12ba3241 - Aurel300
| * 1eb9235be4d - (2 weeks ago) deploy: e8c81a6a2ba6674fa9cae81e7339abbac8e8b237 - bors[bot]
| * ff1f2199a9a - (2 weeks ago) deploy: e8c81a6a2ba6674fa9cae81e7339abbac8e8b237 - bors[bot]
| * 71225f4ce7d - (3 weeks ago) deploy: 734426eb50e6de7454b40694d5a8e843c05d9ee8 - fpoli
| * b3024f688c4 - (3 weeks ago) deploy: 734426eb50e6de7454b40694d5a8e843c05d9ee8 - fpoli
| * 6ef919ef42c - (3 weeks ago) deploy: 734426eb50e6de7454b40694d5a8e843c05d9ee8 - fpoli
| * 699e80bff24 - (3 weeks ago) deploy: 2f46f65f13d48c4fdf574cae33b7cf25f47785c2 - Aurel300
| * b05589b9a42 - (3 weeks ago) deploy: 2f46f65f13d48c4fdf574cae33b7cf25f47785c2 - Aurel300
| * 172b78c9893 - (3 weeks ago) deploy: 638ebd1d7eb755aeff571d50fda4fd948ddfe4e2 - fpoli
| * bccd8fe4e83 - (3 weeks ago) deploy: 638ebd1d7eb755aeff571d50fda4fd948ddfe4e2 - fpoli
| * e75522276f9 - (3 weeks ago) deploy: 693783f61ed2abe34788800b61ed2e84ac1e09d3 - fpoli
| * 53ea0a809fc - (3 weeks ago) deploy: 693783f61ed2abe34788800b61ed2e84ac1e09d3 - fpoli
| * 35bbec0554d - (3 weeks ago) deploy: 98d79c492aae33f57e72716fde4da69956abf5ab - fpoli
| * b09b900fe03 - (3 weeks ago) deploy: 503fe9bd598488ab15e08360c8b2637958507c0c - fpoli
| * 9e89502bd79 - (3 weeks ago) deploy: 98d79c492aae33f57e72716fde4da69956abf5ab - fpoli
| * e7cf926bbd4 - (3 weeks ago) deploy: 503fe9bd598488ab15e08360c8b2637958507c0c - fpoli
| * 7947d932bc3 - (4 weeks ago) deploy: 46488be654aa770797378929a9d1fd265b49aa29 - bors[bot]
| * 7b9831dcff2 - (4 weeks ago) deploy: 46488be654aa770797378929a9d1fd265b49aa29 - bors[bot]
| * aed504cf13d - (4 weeks ago) deploy: 3a6860cdbac39f83b07fe190b0077adcd4500b5c - fpoli
| * 793325de9b7 - (4 weeks ago) deploy: 3a6860cdbac39f83b07fe190b0077adcd4500b5c - fpoli
| * d01c73cd65d - (4 weeks ago) deploy: db0c9740acedf2b2b3d3710ab0937ba7754fa579 - fpoli
| * e1923ce6f0d - (4 weeks ago) deploy: f68d05a88b078ee73f3f2e3ae1ded170699adba2 - fpoli
...
```

### CODE REVIEW

**Comment by Aurel300** [comment]
@fpoli Can you see if [`force-orphan`](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-force-orphan-force_orphan) on the GH publish action does the same thing?

**Comment by fpoli** [comment]
I didn't notice `force_orphan`, thanks. However, it seems that it doesn't work with `keep_files`: https://github.com/peaceiris/actions-gh-pages/issues/455.

**Comment by Aurel300** [comment]
Ok, three things:

- Unless I'm forgetting something, `keep_files` is used only for publishing the benchmark files to GH pages, which as of yet we are not displaying anywhere anyway. If we don't care about these (I don't think GH pages are the right place for this anyway), we can not use the `keep_files` option.
- Speaking of benchmarks, there is a [bunch of them](https://github.com/viperproject/prusti-dev/tree/gh-pages/benchmark-output) in that branch. Do we want to keep them? @vakaras ? Should we replace this with the perfbot @zgrannan ?
- (Very minor.) It seems the [`logo.png` file](https://github.com/viperproject/prusti-dev/blob/master/docs/static/logo.png) got corrupted at some point? At least it does not display for me.

**Comment by fpoli** [comment]
> * Unless I'm forgetting something, `keep_files` is used only for publishing the benchmark files to GH pages, which as of yet we are not displaying anywhere anyway. If we don't care about these (I don't think GH pages are the right place for this anyway), we can not use the `keep_files` option.

Good point. If we remove `keep_files: false` then we should make sure that `destination_dir` is set, or each of the workflows would delete the files published by the others.

> * (Very minor.) It seems the [`logo.png` file](https://github.com/viperproject/prusti-dev/blob/master/docs/static/logo.png) got corrupted at some point? At least it does not display for me.

Mmm, same here.

**Comment by fpoli** [comment]
> > * Unless I'm forgetting something, `keep_files` is used only for publishing the benchmark files to GH pages, which as of yet we are not displaying anywhere anyway. If we don't care about these (I don't think GH pages are the right place for this anyway), we can not use the `keep_files` option.
> 
> Good point. If we remove `keep_files: false` then we should make sure that `destination_dir` is set, or each of the workflows would delete the files published by the others.

Actually, `docs.yml` cannot use `destination_dir` because it needs to publish `index.html` in the root folder. I think our problem is that we have three workflows publishing files instead of just one. If we remove the benchmarks then we can merge the remaining two workflows.

**Comment by fpoli** [comment]
> * Speaking of benchmarks, there is a [bunch of them](https://github.com/viperproject/prusti-dev/tree/gh-pages/benchmark-output) in that branch. Do we want to keep them?

@vakaras? If we remove them then I can merge and simplify the workflows.

**Comment by fpoli** [comment]
Instead of merging this PR, it seems from the discussion above that the best approach is to
1. Remove the benchmark workflow (which we never really used)
2. Merge the two remaining workflows, publishing with the flag [`force_orphan=true`](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-force-orphan-force_orphan).

**Pull request closed without merging**
