### PR TITLE
Generate unfoldings deeper in expressions

### LINKED ISSUE #701: Internal error when pattern matching on a reference inside pure funciton
The following code:

```rust
extern crate prusti_contracts;
use prusti_contracts::*;
struct Wrapper {
   inner: Inner
}

enum Inner {
    SomeThing(Thing), Default
}

struct Thing {}

#[pure]
#[requires(matches!(&m.inner, Inner::SomeThing(_)))]
fn misbehavior_invariant(m: &Wrapper) -> bool {
   match &m.inner {
       Inner::SomeThing(t) => 1,
       _ => unreachable!()
   };
   true
}

fn main(){}
```
yields the following error:

```
error: [Prusti internal error] unhandled verification error: AssertMethodPostconditionTypeInvariants [fold.failed:insufficient.permission] Folding m_Inner$_beg_$_end_(_1.val_ref.f$inner) might fail. There might be insufficient permission to access m_Inner$_beg_$_end_SomeThing(self.enum_SomeThing) (@15.1)
  --> match.rs:15:1
   |
15 | / fn misbehavior_invariant(m: &Wrapper) -> bool {
16 | |    match &m.inner {
17 | |        Inner::SomeThing(t) => 1,
18 | |        _ => unreachable!()
19 | |    };
20 | |    true
21 | | }
   | |_^
```

### LINKED ISSUE #874: optimize_folding doesn't correctly handle disjunctions
The following example fails, due to an incorrect Viper encoding:
```rust
use prusti_contracts::*;
fn main() { }

#[requires(match x {
    Some(v) => *v > 0,
    None => true,
})]
fn foo(x: &mut Option<i32>) {}
```
Specifically we generate:
```boogie
inhale unfolding acc(m_Option$_beg_$i32$_end_Some(_1.val_ref.enum_Some), read$()) in
    unfolding acc(i32(_1.val_ref.enum_Some.f$0), read$()) in
        _1.val_ref.discriminant == 0 || _1.val_ref.enum_Some.f$0.val_int > 0
```
But we should instead be generating:
```boogie
inhale _1.val_ref.discriminant == 0 || (
    unfolding acc(m_Option$_beg_$i32$_end_Some(_1.val_ref.enum_Some), read$()) in
        unfolding acc(i32(_1.val_ref.enum_Some.f$0), read$()) in
            _1.val_ref.enum_Some.f$0.val_int > 0
)
```
(We try to unfold `acc(m_Option$_beg_$i32$_end_Some(_1.val_ref.enum_Some), read$())` even though the enum might be None: `_1.val_ref.discriminant == 0`)

Using `git bisect` I get that the error was introduced by merging in #831 (3a64463127390f52810245cda6f30e34a7b621a6). @Aurel300 any ideas?

May be related to issue #701 though the error is different here and seems easier to fix.

### LINKED ISSUE #892: Nested `unfolding (...) in ...` statements trying to unfold the same predicate
The following Rust program:

```rust
fn main() {}

#[derive(Clone, Copy)]
pub enum Foo {
    Bar,
}

#[trusted]
#[ensures(match result {
    Ok(Some(r)) => r < 100,
    _ => true,
})]
pub fn foo() -> Result<Option<usize>, Foo> {
    unimplemented!()
}

pub fn test() -> Result<usize, Foo> {
    match foo() {
        Err(error) => Err(error),
        Ok(opt) => match opt {
            Some(res) => Ok(res),
            None => Err(Foo::Bar),
        },
    }
}
```

Generates the following error when the `optimize_folding` optimization is disabled:

> error: [Prusti internal error] Prusti encountered an unexpected internal error
>  |
>  = help: This could be caused by too small assertion timeout. Try increasing it by setting the configuration parameter ASSERT_TIMEOUT to a larger value.
>  = note: We would appreciate a bug report: https://github.com/viperproject/prusti-dev/issues/new
>  = note: Details: unregistered verification error: [inhale.failed:insufficient.permission; 0] Inhale might fail. There might be insufficient permission to access `m_Result$_beg_$m_Option$_beg_$usize$_end_$_sep_$struct$m_Foo$_end_Ok(_1.enum_Ok)` (@0.0)

The error goes away and the program verifies okay when enabling the `optimize_folding` optimization. However, this optimization is causing some of my other programs to fail, so I'd like to keep `optimize_folding` disabled. Note that `optimize_folding` will go away when the refactoring lands.

The relevant Viper code looks like this:

```
inhale /* ... */
      unfolding acc(m_Result$_beg_$m_Option$_beg_$usize$_end_$_sep_$struct$m_Foo$_end_Ok(_1.enum_Ok), write) in (
        unfolding acc(m_Option$_beg_$usize$_end_(_1.enum_Ok.f$0), write) in (
          // unfolding acc(m_Result$_beg_$m_Option$_beg_$usize$_end_$_sep_$struct$m_Foo$_end_Ok(_1.enum_Ok), write) in (
            // unfolding acc(m_Option$_beg_$usize$_end_(_1.enum_Ok.f$0), write) in (
              unfolding acc(m_Option$_beg_$usize$_end_Some(_1.enum_Ok.f$0.enum_Some), write) in (
                unfolding acc(usize(_1.enum_Ok.f$0.enum_Some.f$0), write) in _1.enum_Ok.f$0.enum_Some.f$0.val_int
              )
            // )
          // )
        ) < 100
      )
      /* ... */
```

With the 2 `unfolding` expressions commented out it verifies, but when those are present the verification fails (= with `optimize_folding` disabled).

I have a local patch that can solve this when `optimize_folding` is disabled. I'm just creating this issue to create the regression test and PR against :) I'm currently still running some tests, the PR will follow when all tests are passing.

### PR DESCRIPTION
**Pull request by fpoli**
As found in https://github.com/viperproject/prusti-dev/issues/892, the handling of `Downcast` expressions was buggy. This PR fixes that by simplifying how unfoldings are generated, moving them as deep as possible in the expression.

- [x] Fix `optimize_folding` pass, which doesn't correctly handle enumerations.
- [x] Fix performance of the new changes: `get_required_expr_permissions` should not be recursive, otherwise `get_required_stmt_permissions` is quadratic.
- [x] Fix remaining failing UI tests. By generating less `unfold` and more `unfolding`, the counterexamples seem to be less precise.

Fixes https://github.com/viperproject/prusti-dev/issues/892.
Fixes https://github.com/viperproject/prusti-dev/issues/701.
Fixes https://github.com/viperproject/prusti-dev/issues/874.

### CODE REVIEW

**Comment by fpoli** [comment]
@Aurel300 Are you fine with the updated output of the counterexample tests? It seems that by generating less `unfold` and more `unfolding` the counterexamples have more `?` unknown values. In some cases it's good because those values are unrelevant, but in other cases it's less clear.

**Comment by Aurel300** [comment]
Yeah they seem less precise… But let's go for it for now, we are starting a BSc thesis to revamp the counterexamples anyway.

**Comment by fpoli** [comment]
Test `verify/pass/loop-invs/sum-framing.rs` is flaky and is not affected by the disabled `optimize_folding`.

**Comment by fpoli** [comment]
Disabling the broken `optimize_folding` optimization doesn't seem to cause performance issues. Unless there are objections, I'd keep that pass disabled instead of debugging it.

**Comment by fpoli** [comment]
borse merge

**Comment by fpoli** [comment]
bors cancel

(The commits that I pushed are not yet visible in the UI...)

**Comment by fpoli** [comment]
bors merge

**Comment by fpoli** [comment]
borse merge

**Comment by fpoli** [comment]
bors merge

**Comment by fpoli** [comment]
bors merge

**Pull request merged**
