### PR TITLE
Update dependencies (nightly-2021-07-15)

### PR DESCRIPTION
**Pull request by viper-admin**
* [x] Update rustc version to `nightly-2021-07-15`.
* [x] Manualy update outdated dependencies (see the list below).
* [x] Manualy run `cargo update`.

<details><summary>List of direct outdated dependencies:</summary>

```
$ cargo outdated --root-deps-only --workspace

prusti
================
Name        Project  Compat  Latest  Kind    Platform
----        -------  ------  ------  ----    --------
env_logger  0.8.4    ---     0.9.0   Normal  ---

viper
================
Name        Project  Compat  Latest  Kind         Platform
----        -------  ------  ------  ----         --------
env_logger  0.8.4    ---     0.9.0   Development  ---

viper-sys
================
Name        Project  Compat  Latest  Kind    Platform
----        -------  ------  ------  ----    --------
env_logger  0.8.4    ---     0.9.0   Normal  ---

prusti-server
================
Name        Project  Compat  Latest  Kind    Platform
----        -------  ------  ------  ----    --------
env_logger  0.8.4    ---     0.9.0   Normal  ---
futures     0.1.31   ---     0.3.15  Normal  ---
reqwest     0.9.24   ---     0.11.4  Normal  ---
tokio       0.1.22   ---     1.8.1   Normal  ---
warp        0.1.23   ---     0.3.1   Normal  ---

prusti-launch
================
Name  Project  Compat  Latest  Kind    Platform
----  -------  ------  ------  ----    --------
nix   0.21.0   ---     0.22.0  Normal  cfg(unix)

test-crates
================
Name        Project  Compat  Latest  Kind    Platform
----        -------  ------  ------  ----    --------
env_logger  0.8.4    ---     0.9.0   Normal  ---

vir
================
Name       Project  Compat  Latest  Kind    Platform
----       -------  ------  ------  ----    --------
thiserror  1.0.25   ---     1.0.26  Normal  ---

systest
================
Name        Project  Compat  Latest  Kind   Platform
----        -------  ------  ------  ----   --------
env_logger  0.8.4    ---     0.9.0   Build  ---
```
</details>

@fpoli could you take care of this?

### CODE REVIEW

**Comment by vakaras** [comment]
By the way, `type_implements_trait` is removed completely on the current master: https://github.com/rust-lang/rust/commit/c0bd5a584da4f26a1391163a0bdc21b34cf1ba54

**Comment by vakaras** [comment]
> By the way, `type_implements_trait` is removed completely on the current master: [rust-lang/rust@c0bd5a5](https://github.com/rust-lang/rust/commit/c0bd5a584da4f26a1391163a0bdc21b34cf1ba54)

The fix for the latest master: https://github.com/viperproject/prusti-dev/pull/591/commits/d32e8640beec33b83ea5d3a421a1300a7971d100

**Comment by vakaras** [comment]
@Aurel300 You may want to cherry-pick my updates of the UI tests: https://github.com/viperproject/prusti-dev/pull/591/commits/e54b4849b2cc0a6a5cbee4673609be3ef32640b7

**Comment by fpoli** [comment]
@Aurel300 or @vakaras, could you take care of this PR that just got assigned to me?

**Comment by fpoli** [comment]
Ah, this PR is an old one. The bot uses a fixed `auto-update-deps` branch name, so it seems that it ended up force pushing without creating a new PR. If we wish to always have a new PR, we should change the script to append the date to the branch name (e.g. `auto-update-deps-20210-07-15`).

**Comment by vakaras** [comment]
@Aurel300 I can take care of it.

**Comment by vakaras** [comment]
It seems that with the new compiler, Prusti sometimes non-deterministically fails to compile…

**Comment by vakaras** [comment]
@fpoli @Aurel300 The tests sometimes non-deterministically fail due to what seems to be a bug in Clippy. Unless you object, I will merge this PR.

**Comment by Aurel300** [comment]
Should the clippy check not be a separate GH job anyway? Also can we open an issue in their repo?

**Comment by vakaras** [comment]
> Should the clippy check not be a separate GH job anyway?

That is a good idea.

> Also can we open an issue in their repo?

Yes. However, for that we need a minimal repro and I want first to get existentials and other stuff merged.

**Pull request merged**
