### PR TITLE
Update dependencies (nightly-2021-12-01)

### PR DESCRIPTION
**Pull request by viper-admin**
* [x] Update rustc version to `nightly-2021-12-01`.
* [x] Manualy update outdated dependencies (see the list below).
* [x] Manualy run `cargo update`.

<details><summary>List of direct outdated dependencies:</summary>

```
$ cargo outdated --root-deps-only --workspace

info: syncing channel updates for 'nightly-2021-12-01-x86_64-unknown-linux-gnu'
info: latest update on 2021-12-01, rust version 1.59.0-nightly (207c80f10 2021-11-30)
info: downloading component 'cargo'
info: downloading component 'llvm-tools-preview'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustc-dev'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'llvm-tools-preview'
info: installing component 'rust-std'
info: installing component 'rustc'
info: installing component 'rustc-dev'
info: installing component 'rustfmt'
    Updating git repository `https://github.com/rust-lang/cargo.git`
analysis
================
Name        Project  Compat  Latest  Kind    Platform
----        -------  ------  ------  ----    --------
serde_json  1.0.69   ---     1.0.72  Normal  ---

viper-sys
================
Name  Project  Compat  Latest  Kind   Platform
----  -------  ------  ------  ----   --------
ureq  2.3.0    ---     2.3.1   Build  ---

vir
================
Name         Project  Compat  Latest   Kind    Platform
----         -------  ------  ------   ----    --------
derive_more  0.99.16  ---     0.99.17  Normal  ---
syn          1.0.81   ---     1.0.82   Normal  ---

vir-gen
================
Name  Project  Compat  Latest  Kind    Platform
----  -------  ------  ------  ----    --------
syn   1.0.81   ---     1.0.82  Normal  ---

prusti-specs
================
Name        Project  Compat  Latest  Kind    Platform
----        -------  ------  ------  ----    --------
serde_json  1.0.69   ---     1.0.72  Normal  ---
syn         1.0.81   ---     1.0.82  Normal  ---

prusti-server
================
Name     Project  Compat  Latest  Kind    Platform
----     -------  ------  ------  ----    --------
clap     2.33.3   ---     2.34.0  Normal  ---
reqwest  0.10.10  ---     0.11.7  Normal  ---
tokio    0.2.25   ---     1.14.0  Normal  ---
warp     0.2.5    ---     0.3.2   Normal  ---

systest
================
Name  Project  Compat  Latest  Kind   Platform
----  -------  ------  ------  ----   --------
ureq  2.3.0    ---     2.3.1   Build  ---
```
</details>

@fpoli could you take care of this?

### CODE REVIEW

**Comment by fpoli** [comment]
Upgrading `prusti-server`'s dependencies is still blocked by https://github.com/rust-lang/rust/issues/82151 OR https://github.com/hyperium/hyper/issues/2685. Fixing any of them should be enough.

**Comment by fpoli** [comment]
bors merge

**Comment by fpoli** [comment]
bors ping

**Comment by fpoli** [comment]
Why is bors so slow to answer?

**Comment by vakaras** [comment]
bors ping

**Comment by vakaras** [comment]
> Why is bors so slow to answer?

It seems to be simply ignoring you…

**Pull request merged**
