### PR TITLE
Backlog fixes

### LINKED ISSUE #472: [Prusti internal error] unexpected number of type variants: 2 (should be 1)
Similarly to #428, I believe the fact that using iterators which use references might be unsupported as of yet (#143); in this case:

```Rust
fn merge(&self, other: &TwoPSet) -> TwoPSet {
    let mut result = TwoPSet::new();

    result.add_set = self.add_set.union(&other.add_set).copied().collect();
    result.remove_set = self.remove_set.union(&other.remove_set).copied().collect();

    result
}
```

results in the following error:

```Rust
error: [Prusti internal error] unexpected number of type variants: 2 (should be 1)
  --> src/lib.rs:81:5
   |
81 | /     fn merge(&self, other: &TwoPSet) -> TwoPSet {
82 | |         let mut result = TwoPSet::new();
83 | |
84 | |         result.add_set = self.add_set.union(&other.add_set).copied().collect();
...  |
87 | |         result
88 | |     }
   | |_____^
```

[Full code](https://gist.github.com/jmc-figueira/9b0d5229662e15ca8358cdf6196eec90)
[Viper program dump](https://gist.github.com/jmc-figueira/b255fa700841aecc1d7372562c8f4032)

### LINKED ISSUE #623: Missing "unsupported code" error for `Option<&i64>`
The following code:

```rust
pub enum Foo { }

impl Foo {
  pub fn do_thing(&self) -> Option<&i64> {
    return None
  }
}

fn main(){ }
```
results in the error:
```
error: [Prusti internal error] tried to encode a projection that accesses the field 0 of a variant without first downcasting its enumeration std::option::Option<&i64>
 --> test.rs:6:4
```

I think that a reference type inside an Option is not supported in Prusti, so maybe this should be an "unsupported feature" error instead?

### PR DESCRIPTION
**Pull request by viper-admin**
In `test-crates/crates.csv`, replace one `Skip` with `NoCrash` or one `NoCrash` with `NoErrors`. Optionally, also update a crate version. This should be enough to make the `test-crates` test fail because of panics or internal errors. To test a single crate you can use `./target/release/test-crates <FILTER>`, which checks only the crates whose name contains `<FILTER>`.

The purpose of this PR is to fix at least one bug (e.g. convert a panic to an internal error or an internal error to a readable "unsupported" error message).

@JonasAlaif could you take care of this?
Fixes #472, fixes #623

### CODE REVIEW

**Comment by JonasAlaif** [comment]
@fpoli not sure how to check which crates pass? Running e.g. `./target/release/test-crates libc` gives me:
```
[2022-06-03T18:44:10Z INFO  test_crates] Iterate over all 1 crates...
[2022-06-03T18:44:10Z INFO  test_crates] Crate 0/1: crates.io crate libc 0.2.43, test kind: NoErrors
[2022-06-03T18:44:10Z INFO  test_crates] Fetch crate...
[2022-06-03T18:44:12Z INFO  test_crates] Build crate...
[2022-06-03T18:44:13Z WARN  test_crates] Error: ExecutionFailed(ExitStatus(unix_wait_status(256)))
[2022-06-03T18:44:13Z WARN  test_crates] Output:
    [INFO] running `Command { std: "docker" "create" "-v" "/path/to/workspaces/test-crates-builder/builds/build_0/target:/opt/rustwide/target:rw,Z" "-v" "/path/to/workspaces/test-crates-builder/builds/build_0/source:/opt/rustwide/workdir:ro,Z" "-v" "/path/to/workspaces/test-crates-builder/cargo-home:/opt/rustwide/cargo-home:ro,Z" "-v" "/path/to/workspaces/test-crates-builder/rustup-home:/opt/rustwide/rustup-home:ro,Z" "-e" "SOURCE_DIR=/opt/rustwide/workdir" "-e" "CARGO_TARGET_DIR=/opt/rustwide/target" "-e" "CARGO_HOME=/opt/rustwide/cargo-home" "-e" "RUSTUP_HOME=/opt/rustwide/rustup-home" "-w" "/opt/rustwide/workdir" "-m" "1073741824" "--user" "501:20" "--network" "none" "ghcr.io/rust-lang/crates-build-env/linux@sha256:d190cb871061d98bc6d0581d85cb2ecb09a0f8a142ba5463de30be9999fc3251" "/opt/rustwide/cargo-home/bin/cargo" "+nightly-2022-05-16" "check", kill_on_drop: false }`
    [INFO] [stdout] 0f86ff059c8ac620cf43f5bcb11c6f2a17c393e60d8809cd88a590a8c97600ad
    [INFO] running `Command { std: "docker" "start" "-a" "0f86ff059c8ac620cf43f5bcb11c6f2a17c393e60d8809cd88a590a8c97600ad", kill_on_drop: false }`
    [INFO] [stderr] exec /opt/rustwide/cargo-home/bin/cargo: exec format error
    [INFO] running `Command { std: "docker" "inspect" "0f86ff059c8ac620cf43f5bcb11c6f2a17c393e60d8809cd88a590a8c97600ad", kill_on_drop: false }`
    [INFO] running `Command { std: "docker" "rm" "-f" "0f86ff059c8ac620cf43f5bcb11c6f2a17c393e60d8809cd88a590a8c97600ad", kill_on_drop: false }`
    [INFO] [stdout] 0f86ff059c8ac620cf43f5bcb11c6f2a17c393e60d8809cd88a590a8c97600ad
    
[2022-06-03T18:44:13Z ERROR test_crates] Failed to verify 1 crates:
[2022-06-03T18:44:13Z ERROR test_crates]  - crates.io crate libc 0.2.43 (NoErrors)
The application panicked (crashed).
Message:  Failed to verify 1 crates
Location: test-crates/src/main.rs:326
```
And this is a crate that should already `NoErrors`

**Comment by fpoli** [comment]
> @fpoli not sure how to check which crates pass? Running e.g. `./target/release/test-crates libc` gives me:

The `exec /opt/rustwide/cargo-home/bin/cargo: exec format error` is weird. Are you perhaps running `test-crates` from the [Windows subsystem for Linux](https://github.com/mozilla/nixpkgs-mozilla/issues/160)? There also seem to be issues related to [macOS](https://laurabrehm.io/cross-compile-rust-macos-linux.html), but I never encountered them...

**Comment by JonasAlaif** [comment]
> > @fpoli not sure how to check which crates pass? Running e.g. `./target/release/test-crates libc` gives me:
> 
> The `exec /opt/rustwide/cargo-home/bin/cargo: exec format error` is weird. Are you perhaps running `test-crates` from the [Windows subsystem for Linux](https://github.com/mozilla/nixpkgs-mozilla/issues/160)? There also seem to be issues related to [macOS](https://laurabrehm.io/cross-compile-rust-macos-linux.html), but I never encountered them...

I've spent quite some time trying to get a Docker to run on a Linux to run on the Mac but have failed to do so. Instead I'll just try merging this and let someone else figure out which crates now pass (unless bors figures it out and errors)

**Pull request merged**
