### PR TITLE
Issue #718 regression tests

### PR DESCRIPTION
**Pull request by Pointerbender**
The test run for this PR is currently failing, because `x.py test` is not recognizing the error shown by `prusti-rustc` (see #718). This is PR is to show how to reproduce the problem. Once the test suite can recognize the error, these tests can both become regression tests :-)

### CODE REVIEW

**Comment by vakaras** [comment]
Thanks for the PR! Could you please try moving the tests
into`verify-overflow` folder to see whether that fixes the problem?

**Comment by Pointerbender** [comment]
That did the trick! The commit is pushed and I will mark the PR ready for review. Thanks!

**Comment by fpoli** [comment]
As commented in #720, the examples are really useful for debugging etc, but I don't think they should be merged until the issue is fixed.

**Comment by Pointerbender** [comment]
Temporarily moving this PR to "draft" status until PR #720 is merged, at which point I will rebase this PR against the latest master branch, so that the CI will properly include the test cases part of this PR in `verify_partial` (otherwise in theory there could be a situation where these tests are not tested, but are still merged onto the master branch).

**Comment by Pointerbender** [comment]
The PR is updated with the test suite for `verify_partial` from the master branch. I moved the new regression tests for #718 into the `verify_partial` folder and this PR is ready for review/merging.

**Review by vakaras — APPROVED** [review]
LGTM

**Comment by vakaras** [comment]
Thank you!

**Pull request merged**
