### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by vakaras**
Continue refactoring.

### CODE REVIEW

**Comment by vakaras** [comment]
bors ping

**Comment by vakaras** [comment]
bors retry

**Comment by vakaras** [comment]
> Build failed:
> 
>     * [test-crates](https://github.com/viperproject/prusti-dev/runs/5761867363?check_suite_focus=true)

@fpoli This seems to be a flaky test: the code I changed should not be executed by `test-crates` and, therefore, should have no impact on performance.

**Comment by fpoli** [comment]
> > Build failed:
> > ```
> > * [test-crates](https://github.com/viperproject/prusti-dev/runs/5761867363?check_suite_focus=true)
> > ```
> 
> @fpoli This seems to be a flaky test: the code I changed should not be executed by `test-crates` and, therefore, should have no impact on performance.

I agree. Could you set `serde_test` and `sdl2-sys` to `Skip` in `test-crates/crates.csv`?

**Pull request merged**
