### PR TITLE
Support Mac in x.py

### PR DESCRIPTION
**Pull request by Aurel300**
`JAVA_HOME` is detected using `/usr/libexec/java_home`, and the library is a `.dylib` rather than an `.so`. I also added `DYLD_LIBRARY_PATH` in addition to `LD_LIBRARY_PATH`, since the former is what Mac uses for configuring the dynamic linker. It seems to work with only the latter, but that might be a different problem.

I also wonder if we should update:

 - [ ] `Makefile` - remove it?
 - [ ] `docker/artefact.Dockerfile` - does a `make release` on L12
 - [ ] `evaluation/artifact/preparation.rst` - `make release` (this file is quite old as well)
 - [ ] `README.md` - `make run RUN_FILE=path/to/the/program_to_be_verified.rs`

### CODE REVIEW

**Review by vakaras — APPROVED** [review]
Thanks!

**Comment by vakaras** [comment]
> I also wonder if we should update:

I agree that we should fix these too. Also, we should enable CI for Mac OS now.

**Comment by Aurel300** [comment]
> I agree that we should fix these too. Also, we should enable CI for Mac OS now.

Sounds good. Was it disabled in a particular commit? Or should I just copy the `rustc-update` job in the GH workflow?

**Comment by vakaras** [comment]
We never had Mac OS CI on GitHub.

**Comment by fpoli** [comment]
> * `Makefile` - remove it?

I think yes. It's much easier to maintain the `x.py` cross-platform than the `Makefile`.

**Pull request merged**
