### PR TITLE
Update dependencies (rustc nightly-2023-06-15, viper v-2023-05-17-0733)

### PR DESCRIPTION
**Pull request by viper-admin**
* [x] Update Viper version to `v-2023-05-17-0733`.
* [x] Update rustc version to `nightly-2023-06-15`.
* [x] Run `cargo audit` and fix the issues.
* [x] Manualy update outdated dependencies (see the list below).
* [x] Manualy run `cargo update`.

<details><summary>List of direct outdated dependencies:</summary>

```
$ mv prusti-contracts/Cargo.toml prusti-contracts/Cargo_disabled.toml
$ cargo outdated --root-deps-only --workspace

info: syncing channel updates for 'nightly-2023-06-15-x86_64-unknown-linux-gnu'
info: latest update on 2023-06-15, rust version 1.72.0-nightly (8c74a5d27 2023-06-14)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'llvm-tools'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustc-dev'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'llvm-tools'
info: installing component 'rust-std'
info: installing component 'rustc'
info: installing component 'rustc-dev'
info: installing component 'rustfmt'
    Updating git repository `https://github.com/rust-lang/cargo.git`
warning: skipping duplicate package `case` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/init/simple_git_ignore_exists/out`
warning: skipping duplicate package `case` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/init/creates_library_when_instructed_and_has_bin_file/out`
warning: skipping duplicate package `case` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/init/bin_already_exists_implicit/out`
warning: skipping duplicate package `case` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/init/simple_hg/out`
warning: skipping duplicate package `case` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/init/simple_lib/out`
warning: skipping duplicate package `case` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/init/inferred_lib_with_git/out`
warning: skipping duplicate package `case` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/init/git_ignore_exists_no_conflicting_entries/out`
warning: skipping duplicate package `case` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/init/lib_already_exists_src/out`
warning: skipping duplicate package `case` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/init/bin_already_exists_implicit_namesrc/out`
warning: skipping duplicate package `case` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/init/ignores_failure_to_format_source/out`
warning: skipping duplicate package `case` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/init/bin_already_exists_explicit/out`
warning: skipping duplicate package `foo` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/init/git_autodetect/out`
warning: skipping duplicate package `case` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/init/formats_source/out`
warning: skipping duplicate package `case` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/init/inferred_bin_with_git/out`
warning: skipping duplicate package `case` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/init/mercurial_autodetect/out`
warning: skipping duplicate package `case` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/init/creates_binary_when_instructed_and_has_lib_file/out`
warning: skipping duplicate package `case` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/init/fossil_autodetect/out`
warning: skipping duplicate package `case` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/init/bin_already_exists_explicit_nosrc/out`
warning: skipping duplicate package `case` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/init/creates_binary_when_both_binlib_present/out`
warning: skipping duplicate package `case` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/init/explicit_bin_with_git/out`
warning: skipping duplicate package `case` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/init/pijul_autodetect/out`
warning: skipping duplicate package `case` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/init/bin_already_exists_implicit_nosrc/out`
warning: skipping duplicate package `case` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/init/simple_bin/out`
warning: skipping duplicate package `case` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/init/bin_already_exists_implicit_namenosrc/out`
warning: skipping duplicate package `case` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/init/simple_git/out`
warning: skipping duplicate package `case` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/init/simple_hg_ignore_exists/out`
warning: skipping duplicate package `case` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/init/auto_git/out`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_no_optional/in`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/list_features_path/in/primary`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/registry/in`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_rename_with_rename_noop/in`
warning: skipping duplicate package `foo` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_workspace_dep/in/dependency`
warning: skipping duplicate package `bar` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_workspace_dep/in/primary`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/workspace_path_dev/in/primary`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_optional/in`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_version_with_git/in`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/git_registry/in`
warning: skipping duplicate package `cargo-list-test-fixture-dependency` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/workspace_path/in/dependency`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/workspace_path/in/primary`
warning: skipping duplicate package `your-face` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_path_noop/in/dependency`
warning: skipping duplicate package `foo` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/invalid_key_overwrite_inherit_dependency/in/dependency`
warning: skipping duplicate package `bar` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/invalid_key_overwrite_inherit_dependency/in/primary`
warning: skipping duplicate package `cargo-list-test-fixture-dependency` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/build_prefer_existing_version/in/dependency`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_features/in`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_optional_with_no_optional/in`
warning: skipping duplicate package `cargo-list-test-fixture-dependency` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/path_inferred_name/in/dependency`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/path_inferred_name/in/primary`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_default_features_with_no_default_features/in`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_inline_features/in`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/deprecated_default_features/in`
warning: skipping duplicate package `cargo-list-test-fixture-dependency` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_version_with_path/in/dependency`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_version_with_path/in/primary`
warning: skipping duplicate package `foo` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/unknown_inherited_feature/in/dependency`
warning: skipping duplicate package `bar` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/unknown_inherited_feature/in/primary`
warning: skipping duplicate package `cargo-list-test-fixture-dependency` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_git_with_path/in/dependency`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_git_with_path/in/primary`
warning: skipping duplicate package `cargo-list-test-fixture-dependency` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/invalid_path_name/in/dependency`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/invalid_path_name/in/primary`
warning: skipping duplicate package `cargo-list-test-fixture-dependency` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/path_dev/in/dependency`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/path_dev/in/primary`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/add-basic.in`
warning: skipping duplicate package `your-face` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_name_dev_noop/in/dependency`
warning: skipping duplicate package `cargo-list-test-fixture-dependency` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_path_with_version/in/dependency`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_path_with_version/in/primary`
warning: skipping duplicate package `cargo-list-test-fixture-dependency` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/path/in/dependency`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/path/in/primary`
warning: skipping duplicate package `foo` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/invalid_key_inherit_dependency/in/dependency`
warning: skipping duplicate package `bar` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/invalid_key_inherit_dependency/in/primary`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_with_rename/in`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/deprecated_section/in`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/preserve_sorted/in`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_rename_with_no_rename/in`
warning: skipping duplicate package `foo` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/merge_activated_features/in/dependency`
warning: skipping duplicate package `bar` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/merge_activated_features/in/primary`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_rename_with_rename/in`
warning: skipping duplicate package `foo` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_inherit_optional_noop/in/dependency`
warning: skipping duplicate package `bar` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_inherit_optional_noop/in/primary`
warning: skipping duplicate package `foo` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/detect_workspace_inherit_optional/in/dependency`
warning: skipping duplicate package `bar` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/detect_workspace_inherit_optional/in/primary`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_no_default_features/in`
warning: skipping duplicate package `foo` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_inherit_noop/in/dependency`
warning: skipping duplicate package `bar` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_inherit_noop/in/primary`
warning: skipping duplicate package `foo` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/invalid_key_rename_inherit_dependency/in/dependency`
warning: skipping duplicate package `bar` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/invalid_key_rename_inherit_dependency/in/primary`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/require_weak/in`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_no_optional_with_optional/in`
warning: skipping duplicate package `optional-dep` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/path_inferred_name_conflicts_full_feature/in/optional`
warning: skipping duplicate package `your-face` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/path_inferred_name_conflicts_full_feature/in/dependency`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/path_inferred_name_conflicts_full_feature/in/primary`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_no_default_features_with_default_features/in`
warning: skipping duplicate package `cargo-list-test-fixture-dependency` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/manifest_path_package/in/dependency`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/manifest_path_package/in/primary`
warning: skipping duplicate package `foo` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_workspace_dep_features/in/dependency`
warning: skipping duplicate package `bar` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_workspace_dep_features/in/primary`
warning: skipping duplicate package `foo` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_inherit_features_noop/in/dependency`
warning: skipping duplicate package `bar` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_inherit_features_noop/in/primary`
warning: skipping duplicate package `foo` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/detect_workspace_inherit/in/dependency`
warning: skipping duplicate package `bar` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/detect_workspace_inherit/in/primary`
warning: skipping duplicate package `cargo-list-test-fixture-dependency` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/workspace_name/in/dependency`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/workspace_name/in/primary`
warning: skipping duplicate package `cargo-list-test-fixture-dependency` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/dev_prefer_existing_version/in/dependency`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/overwrite_default_features/in`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/preserve_unsorted/in`
warning: skipping duplicate package `cargo-list-test-fixture-dependency` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/path_normalized_name/in/dependency`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/path_normalized_name/in/primary`
warning: skipping duplicate package `optional-dep` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/list_features_path_no_default/in/optional`
warning: skipping duplicate package `your-face` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/list_features_path_no_default/in/dependency`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/list_features_path_no_default/in/primary`
warning: skipping duplicate package `cargo-list-test-fixture` found at `/home/runner/.cargo/git/checkouts/cargo-e7ff1db891893a9e/17f8088/tests/testsuite/cargo_add/features_preserve/in`
error: failed to select a version for `git2`.
    ... required by package `rustwide v0.16.0`
    ... which satisfies dependency `rustwide = "^0.16.0"` of package `test-crates v0.1.0 (/tmp/cargo-outdated2Ag3Lj/test-crates)`
versions that meet the requirements `^0.17.0` are: 0.17.2, 0.17.1, 0.17.0

the package `git2` links to the native library `git2`, but it conflicts with a previous package which links to `git2` as well:
package `git2 v0.14.2`
    ... which satisfies dependency `git2 = "^0.14.2"` of package `cargo-test-support v0.1.0 (https://github.com/rust-lang/cargo.git?rev=17f8088#17f8088d)`
    ... which satisfies git dependency `cargo-test-support` (locked to 0.1.0) of package `prusti-tests v0.2.0 (/tmp/cargo-outdated2Ag3Lj/prusti-tests)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the links ='git2' value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `git2` which could resolve this conflict
cargo outdated failed to execute

$ mv prusti-contracts/Cargo_disabled.toml prusti-contracts/Cargo.toml
```
</details>

@fpoli could you take care of this?

### CODE REVIEW

**Comment by fpoli** [comment]
@JonasAlaif? The oldest open PR to update the dependencies was assigned to you.

**Comment by JonasAlaif** [comment]
I suggest that we all contribute to this PR and jump straight to the latest version. Let's take turns and lock the PR (with a comment) and then spend e.g. 30mins working on it. I can start, so locking until I push.

**Comment by JonasAlaif** [comment]
@fpoli, @Aurel300, @vakaras you guys can continue. There's a `NonMutatingUseContext::UniqueBorrow` that was removed but I skipped, seems that @fpoli wrote that code so I'll leave it up to him and the `viper.silver.ast.AnnotationInfo` constructor changed which I didn't know how to update correctly so also skipped

**Comment by fpoli** [comment]
> `PlaceContext::NonMutatingUse(NonMutatingUseContext::UniqueBorrow) => todo!(),`

Thanks! I don't have time now to try, but if what above is the only `UniqueBorrow` usage then it's enough to remove that unimplemented case from the match.

**Comment by vakaras** [comment]
> @fpoli, @Aurel300, @vakaras you guys can continue. 

The errors I am getting now are about `ty::EarlyBinder` and traits, so I guess @Aurel300 is the most competent here.

> the `viper.silver.ast.AnnotationInfo` constructor changed which I didn't know how to update correctly so also skipped

I do not get any errors about this. Also, `build.rs` seems to match the one on my [branch](https://github.com/viperproject/prusti-dev/blob/refactorings/viper-sys/build.rs) which compiles on Viper `master` branch.

**Comment by JonasAlaif** [comment]
Ah I forgot to do a `./x.py setup`, ignore the `viper.silver.ast.AnnotationInfo`

**Comment by JonasAlaif** [comment]
@fpoli @Aurel300 your turn

**Comment by vakaras** [comment]
@fpoli Your turn.

**Comment by fpoli** [comment]
Next bug: `prusti_interface::specs::SpecCollector::ensure_local_mirs_fetched` fails with `attempted to read from stolen value: rustc_middle::mir::Body` when trying to load the following `def_id`, which is the first body that we attempt to load.
```
DefId(0:128 ~ prusti_contracts[07ec]::core_spec::{impl#1}::prusti_pre_item_unwrap_200eac6aca734d22acbb93f793512509), core_spec::PrustiStructcoreresultResult_2b75670183924a508530e94c5aaf8087::<T, E>::prusti_pre_item_unwrap_200eac6aca734d22acbb93f793512509
```

**Comment by fpoli** [comment]
@Aurel300 @vakaras @JonasAlaif

**Comment by fpoli** [comment]
@JonasAlaif the new error is related to loading the body of external items.

**Comment by JonasAlaif** [comment]
@fpoli I don't think that's the case no, the error happens when trying to load a local body of `prusti_contracts` while compiling `prusti_contracts` - it isn't related to external items. Or did you find something else to indicate that?

**Comment by JonasAlaif** [comment]
The issue instead seems to be that [`tcx.mir_promoted`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/context/struct.TyCtxt.html#method.mir_promoted) now returns a value that's already stolen. I have no idea what causes it to do that now when it didn't before. Maybe someone else has dealt with this issue already before?

**Comment by fpoli** [comment]
> @fpoli I don't think that's the case no, the error happens when trying to load a local body of `prusti_contracts` while compiling `prusti_contracts` - it isn't related to external items. Or did you find something else to indicate that?

I didn't notice that it happens while compiling `prusti_contracts`.

**Comment by fpoli** [comment]
My debugging session, in case it's useful for the future:
* The only MIR query that consumes `mir_promoted` is `mir_drops_elaborated_and_const_checked`.
    * The dependency graph of the queries can be dumped using `-Zdump-dep-graph -Zquery-dep-graph`.
    * The queries that *steal* can be identified by searching in `rust/compiler/rustc_interface/src
/passes.rs` for `Steal<..>` in the return types.
* `mir_drops_elaborated_and_const_checked` is called by `passes::analysis`.
    * To see who calls `mir_drops_elaborated_and_const_checked`, one can
        1. override the query in our `prusti/src/callbacks.rs`
        2. make the new query panic when the `def_id` corresponds to the one in the "attempted to read from stolen value" error.
    * The rustc PR that adds the query call is https://github.com/rust-lang/rust/pull/110107.

**Solution:** Clone the MIR body in a query override before it gets stolen. In the fix that I pushed I'm reusing the existing `mir_borrowck` override, although it might be more efficient to add a new override for `mir_promoted` so that we don't also clone Polonius facts.

**Comment by JonasAlaif** [comment]
@fpoli we can use the new `consumers::ConsumerOptions::PoloniusOutputFacts` argument to `get_body_with_borrowck_facts` to avoid using Polonius when it's not needed. E.g.
```
let consumer_opts = if is_spec_fn(tcx, def_id.to_def_id()) {
  consumers::ConsumerOptions::RegionInferenceContext
} else {
   consumers::ConsumerOptions::PoloniusOutputFacts
}
...
```

Why was `if !config::no_verify()` removed in `fn config` though? This was needed to avoid running polonius on dependencies, without that one cannot verify something that depends on some of the popular crates.io crates (which happen to have fns with massive bodies). I guess a fix could be to add `|| config::no_verify()` to the above condition.

**Comment by fpoli** [comment]
> avoid using Polonius when it's not needed.

Yeah I thought about that too, but then the documentation of `get_body_with_borrowck_facts` states that that field is ignored because enabling Polonius via `-Z` takes precedence. I didn't check if the documentation is lying, or what happens when Prusti runs on dependencies for which we don't force Polonius via `-Z`.

> Why was if `!config::no_verify()` removed in `fn config` though?

I remember that the spec collector was trying to load the body of a function whose borrow checking was *not* using our override, and removing that condition was enough to force our override. Anyway, I agree with your comment and it's better to double check. It's possible that I was testing two changes at once.

**Comment by JonasAlaif** [comment]
I wrote that documentation haha, we have been running without `-z` Polonius for a while now (unless someone reenabled it). The flowistry people made a PR a while back where `get_body_with_borrowck_facts` would always run polonius regardless of the flag and thus the flag was unnecessary (and now I changed the `get_body_with_borrowck_facts` code that Polonius runs iff `PoloniusOutputFacts` is passed or `-z` Polonius is enabled).

It does makes sense that the spec collector tries to load a body when `config::no_verify()`, it'll be doing that for e.g. pure fns or spec fns to export them for cross-crate (now that those aren't loaded with `mir_promoted`). I think that we'll never need brrowck facts in that case though. So we should do:
```rust
let consumer_opts = if is_spec_fn(tcx, def_id.to_def_id()) || config::no_verify() {
    consumers::ConsumerOptions::RegionInferenceContext
} else {
    consumers::ConsumerOptions::PoloniusOutputFacts
}
```

**Comment by fpoli** [comment]
> we have been running without -z Polonius for a while now

Oh, great! Then we should definitely add that switch, yes.

**Comment by JonasAlaif** [comment]
@vakaras could you take a look at the current error: it's at `prusti-viper/src/encoder/mir/pure/interpreter/interpreter_high.rs:1073`

**Comment by Aurel300** [comment]
> could you take a look at the current error: it's at `prusti-viper/src/encoder/mir/pure/interpreter/interpreter_high.rs:1073`

@JonasAlaif Fairly sure `AscribeUserType` should also be a no-op in pure code.

**Comment by JonasAlaif** [comment]
@fpoli your fix with using `get_body_with_borrowck_facts` for all bodies doesn't seem to fully work. I guess the issue is that we get back a body with regions relabelled and other rustc functions don't understand that.

**Comment by JonasAlaif** [comment]
@vakaras @Aurel300 your turn

**Comment by vakaras** [comment]
@Aurel300 Your turn.

**Pull request merged**
