### PR TITLE
Quantification over non-integer types

### PR DESCRIPTION
**Pull request by vakaras**
A rebased version of #326 

cc @tillarnold

### CODE REVIEW

**Comment by vakaras** [comment]
@tillarnold I have deleted some garbage commits and rebased. So you may want to start working on this branch instead of your own.

**Comment by fpoli** [comment]
Please don't forget the review from the other PR.

**Comment by fpoli** [comment]
> A rebased version of #326

Can we then close that?

**Comment by tillarnold** [comment]
@vakaras I don't have push access to the repository so I don't think I can work on this branch.

**Comment by vakaras** [comment]
> @vakaras I don't have push access to the repository so I don't think I can work on this branch.

This PR should have all the changes from your PR. So, you could delete your PR and fork this one.

**Comment by vakaras** [comment]
@Aurel300 This PR adds hacky support for quantification over non-integer types. Unless you object, I will merge it after the CI passes. There should be no changes to behaviour unless `PRUSTI_ENABLE_PURIFICATION_OPTIMIZATION` is set to `true`.

**Pull request merged**
