### PR TITLE
Add all **/basic.rs tests to quick tests.

### PR DESCRIPTION
**Pull request by frececroka**

### CODE REVIEW

**Comment by fpoli** [comment]
I would prefer moving the examples to the `quick/` folders, to avoid testing them twice in the full-tests.

**Comment by frececroka** [comment]
That makes sense. I made a prototype that splits the verification tests into a "core" set of the most essential tests, and an "extended" set that included additional tests. I'll push something later, so you can look at it to see if you like it. Otherwise we can just stick with the "quick" folder for now (I'll move the symlinked files then).

**Comment by fpoli** [comment]
I would prefer not adding one more layer of folders (`tests/*/core/**` and `tests/*/extended/**`).

To decide what goes in `quick`, I could try to gather all logs of Jenkins tests that run in the past ~2 years, to find out what are the tests that fail more often.

**Comment by frececroka** [comment]
Ah you found the branch ;) I forgot to add it to the PR, sorry.

Sure, I'll just move the `basic.rs` tests to the `quick` folder. The idea to check Jenkins for the tests that fail often is nice!

**Comment by fpoli** [comment]
Here is the list of tests that failed in the last 2 years, with their frequency:

<details>
 <summary>Expand</summary>

```
      1 test [compile-fail] fail/addons/generics-basic-3-2.rs ... FAILED
      1 test [compile-fail] fail/addons/generics-basic-3-4.rs ... FAILED
      1 test [compile-fail] fail/addons/generics-basic-3-6.rs ... FAILED
      1 test [compile-fail] fail/addons/generics-basic-4-1.rs ... FAILED
      1 test [compile-fail] fail/addons/invariants-basic-4.rs ... FAILED
      1 test [compile-fail] fail/addons/invariants-basic-6.rs ... FAILED
      1 test [compile-fail] fail/addons/invariants-combined.rs ... FAILED
      1 test [compile-fail] fail/addons/invariants-typestates-basic-2-1.rs ... FAILED
      1 test [compile-fail] fail/addons/invariants-typestates-basic-2-2.rs ... FAILED
      1 test [compile-fail] fail/addons/invariants-typestates-basic-2-3.rs ... FAILED
      1 test [compile-fail] fail/addons/pledges-basic-2-4.rs ... FAILED
      1 test [compile-fail] fail/addons/traits-basic-norm-prov-defi-post.rs ... FAILED
      1 test [compile-fail] fail/addons/traits-basic-norm-prov-impl-post.rs ... FAILED
      1 test [compile-fail] fail/addons/traits-basic-norm-reqd-impl-post.rs ... FAILED
      1 test [compile-fail] fail/addons/traits-combined.rs ... FAILED
      1 test [compile-fail] fail/addons/typestates-basic-1-3.rs ... FAILED
      1 test [compile-fail] fail/addons/typestates-combined.rs ... FAILED
      1 test [compile-fail] fail/erdinm/generics-basic-5-1.rs ... FAILED
      1 test [compile-fail] fail/erdinm/generics-basic-5-2.rs ... FAILED
      1 test [compile-fail] fail/erdinm/generics-combined.rs ... FAILED
      1 test [compile-fail] fail/erdinm/generics-special-1.rs ... FAILED
      1 test [compile-fail] fail/erdinm/invariants-basic-1.rs ... FAILED
      1 test [compile-fail] fail/erdinm/invariants-basic-2.rs ... FAILED
      1 test [compile-fail] fail/erdinm/invariants-basic-3.rs ... FAILED
      1 test [compile-fail] fail/erdinm/invariants-basic-4.rs ... FAILED
      1 test [compile-fail] fail/erdinm/invariants-basic-5.rs ... FAILED
      1 test [compile-fail] fail/erdinm/invariants-basic-6.rs ... FAILED
      1 test [compile-fail] fail/erdinm/invariants-combined.rs ... FAILED
      1 test [compile-fail] fail/erdinm/invariants-pledges-2-1.rs ... FAILED
      1 test [compile-fail] fail/erdinm/invariants-pledges-3-2.rs ... FAILED
      1 test [compile-fail] fail/erdinm/invariants-typestates-basic-2-1.rs ... FAILED
      1 test [compile-fail] fail/erdinm/invariants-typestates-basic-2-2.rs ... FAILED
      1 test [compile-fail] fail/erdinm/typestates-basic-1-1.rs ... FAILED
      1 test [compile-fail] fail-overflow/overflow/pure.rs ... FAILED
      1 test [compile-fail] fail/pure-fn/wrong-fn-post.rs ... FAILED
      1 test [compile-fail] fail/pure-fn/wrong-ref-mut-arg.rs ... FAILED
      1 test [compile-fail] fail/shared-borrows/mut-borrows.rs ... FAILED
      1 test [compile-fail] fail/trait-contracts-refinement/post.rs ... FAILED
      1 test [compile-fail] fail/trait-contracts-refinement/pre.rs ... FAILED
      1 test [compile-fail] fail/with-spec/wrong-method.rs ... FAILED
      1 test [run-pass] pass/addons/generics-basic-2.rs ... FAILED
      1 test [run-pass] pass/addons/generics-basic-3.rs ... FAILED
      1 test [run-pass] pass/addons/generics-basic-4.rs ... FAILED
      1 test [run-pass] pass/addons/generics-basic-5.rs ... FAILED
      1 test [run-pass] pass/addons/generics-basic-7.rs ... FAILED
      1 test [run-pass] pass/addons/generics-basic-8.rs ... FAILED
      1 test [run-pass] pass/addons/invariants-basic-2.rs ... FAILED
      1 test [run-pass] pass/addons/invariants-basic-3.rs ... FAILED
      1 test [run-pass] pass/addons/invariants-pledges-2.rs ... FAILED
      1 test [run-pass] pass/addons/invariants-pledges-3.rs ... FAILED
      1 test [run-pass] pass/addons/invariants-pledges-4.rs ... FAILED
      1 test [run-pass] pass/addons/invariants-typestates-basic-1.rs ... FAILED
      1 test [run-pass] pass/addons/pledges-basic-1.rs ... FAILED
      1 test [run-pass] pass/addons/pledges-basic-2.rs ... FAILED
      1 test [run-pass] pass/addons/traits-basic-norm-prov-call-post.rs ... FAILED
      1 test [run-pass] pass/addons/traits-basic-norm-prov-call-pre.rs ... FAILED
      1 test [run-pass] pass/addons/typestates-basic-1.rs ... FAILED
      1 test [run-pass] pass/expiring-loans/track-moved.rs ... FAILED
      1 test [run-pass] pass/loop-invs/loop_in_guard.rs ... FAILED
      1 test [run-pass] pass-overflow/div_rem_64.rs ... FAILED
      1 test [run-pass] pass-overflow/iso_week_days.rs ... FAILED
      1 test [run-pass] pass-overflow/others.rs ... FAILED
      1 test [run-pass] pass-overflow/overflow/calls.rs ... FAILED
      1 test [run-pass] pass-overflow/rosetta/100_doors_generic.rs ... FAILED
      1 test [run-pass] pass-overflow/rosetta/Binary_search_shared.rs ... FAILED
      1 test [run-pass] pass-overflow/rosetta/Singly_Linked_List.rs ... FAILED
      1 test [run-pass] pass-overflow/rosetta/Towers_of_Hanoi.rs ... FAILED
      1 test [run-pass] pass-overflow/rosetta/Towers_of_Hanoi_spec.rs ... FAILED
      1 test typecheck_test ... FAILED
      1 test [ui] ui/failing-postcondition.rs ... FAILED
      1 test [ui] ui/non-pure-function.rs ... FAILED
      1 test [ui] ui/warnings.rs ... FAILED
      2 test [compile-fail] fail/erdinm/invariants-typestates-basic-1-1.rs ... FAILED
      2 test [compile-fail] fail/erdinm/invariants-typestates-basic-1-2.rs ... FAILED
      2 test [compile-fail] fail/erdinm/invariants-typestates-basic-1-3.rs ... FAILED
      2 test [compile-fail] fail/issues/issue-81-ops.rs ... FAILED
      2 test [compile-fail] fail/issues/issue-81-pure-fn.rs ... FAILED
      2 test [compile-fail] fail/issues/issue-81.rs ... FAILED
      2 test [compile-fail] fail-overflow/overflow/div_u64.rs ... FAILED
      2 test [compile-fail] fail-overflow/overflow/loops.rs ... FAILED
      2 test [compile-fail] fail/with-spec/unsigned_ints.rs ... FAILED
      2 test [run-pass] pass/demos/append-sorted.rs ... FAILED
      2 test [run-pass] pass/erdinm/traits-basic-norm-prov-defi-post.rs ... FAILED
      2 test [run-pass] pass/erdinm/traits-basic-norm-prov-impl-post.rs ... FAILED
      2 test [run-pass] pass/erdinm/traits-basic-norm-reqd-impl-post.rs ... FAILED
      2 test [run-pass] pass/foobar/invariants-pledges-2.rs ... FAILED
      2 test [run-pass] pass/issues/issue-104.rs ... FAILED
      2 test [run-pass] pass/issues/issue-170.rs ... FAILED
      2 test [run-pass] pass-overflow/overflow/pure.rs ... FAILED
      2 test [run-pass] pass-overflow/rosetta/Heapsort_generic.rs ... FAILED
      2 test [run-pass] pass-overflow/uint.rs ... FAILED
      2 test [ui] ui/parenthesis.rs ... FAILED
      2 test [ui] ui/simple_and.rs ... FAILED
      2 test [ui] ui/simple_forall.rs ... FAILED
      2 test [ui] ui/simple_imply.rs ... FAILED
      3 test [compile-fail] fail/pure-fn/fail-pc.rs ... FAILED
      3 test [compile-fail] fail/shared-borrows/loops.rs ... FAILED
      3 test [compile-fail] fail/shared-borrows/reborrowing.rs ... FAILED
      3 test [compile-fail] fail/with-spec/loops-before-inside.rs ... FAILED
      3 test [compile-fail] fail/with-spec/wrong-trait.rs ... FAILED
      3 test [run-pass] pass/addons/traits-basic-norm-reqd-call-post.rs ... FAILED
      3 test [run-pass] pass/addons/traits-basic-norm-reqd-call-pre.rs ... FAILED
      3 test [run-pass] pass/issues/issue-128.rs ... FAILED
      3 test [run-pass] pass/issues/issue-46-old-expr.rs ... FAILED
      3 test [run-pass] pass/loop-invs/complex_guard.rs ... FAILED
      3 test [run-pass] pass/mut-borrows/empty-method.rs ... FAILED
      3 test [run-pass] pass/mut-borrows/move.rs ... FAILED
      3 test [run-pass] pass/no-annotations/empty-function.rs ... FAILED
      3 test [run-pass] pass/no-annotations/external-call.rs ... FAILED
      3 test [run-pass] pass/no-annotations/option-2.rs ... FAILED
      3 test [run-pass] pass/no-annotations/paths.rs ... FAILED
      3 test [run-pass] pass-overflow/larger/first-final.rs ... FAILED
      3 test [run-pass] pass-overflow/overflow/loops.rs ... FAILED
      3 test [run-pass] pass-overflow/rosetta/Binary_search_shared_monomorphised.rs ... FAILED
      3 test [run-pass] pass/pure-fn/pure_ranges.rs ... FAILED
      3 test [run-pass] pass/with-spec/vec-wrapper.rs ... FAILED
      3 test [ui] ui/failures.rs ... FAILED
      4 test [compile-fail] fail/erdinm/traits-basic-norm-prov-call-pre.rs ... FAILED
      4 test [compile-fail] fail/erdinm/traits-basic-norm-prov-defi-post.rs ... FAILED
      4 test [compile-fail] fail/erdinm/traits-basic-norm-prov-impl-post.rs ... FAILED
      4 test [compile-fail] fail/erdinm/traits-basic-norm-reqd-call-pre.rs ... FAILED
      4 test [compile-fail] fail/erdinm/traits-basic-norm-reqd-impl-post.rs ... FAILED
      4 test [compile-fail] fail/erdinm/traits-combined.rs ... FAILED
      4 test [compile-fail] fail/erdinm/typestates-combined.rs ... FAILED
      4 test [compile-fail] fail/issues/issue-90.rs ... FAILED
      4 test [compile-fail] fail/magic-wands/wrong-wand-identity2.rs ... FAILED
      4 test [compile-fail] fail/pure-fn/wrong-simple-fn.rs ... FAILED
      4 test [run-pass] pass/erdinm/generics-basic-1.rs ... FAILED
      4 test [run-pass] pass/erdinm/traits-basic-norm-prov-defi-pre.rs ... FAILED
      4 test [run-pass] pass/erdinm/traits-basic-norm-prov-impl-pre.rs ... FAILED
      4 test [run-pass] pass/erdinm/traits-basic-norm-reqd-impl-pre.rs ... FAILED
      4 test [run-pass] pass/expiring-loans/issue-25-simpl.rs ... FAILED
      4 test [run-pass] pass/generic/linear_search.rs ... FAILED
      4 test [run-pass] pass/initialization/deref.rs ... FAILED
      4 test [run-pass] pass/issues/issue-138.rs ... FAILED
      4 test [run-pass] pass/no-annotations/consume-call.rs ... FAILED
      4 test [run-pass] pass/no-annotations/join.rs ... FAILED
      4 test [run-pass] pass/no-annotations/match-char.rs ... FAILED
      4 test [run-pass] pass/no-annotations/use-box.rs ... FAILED
      4 test [run-pass] pass-overflow/issues/issue-104.rs ... FAILED
      4 test [run-pass] pass-overflow/nll-rfc/borrow_first.rs ... FAILED
      4 test [run-pass] pass-overflow/nll-rfc/case1-overflow.rs ... FAILED
      4 test [run-pass] pass-overflow/precise_mul_add_assign.rs ... FAILED
      4 test [run-pass] pass/shared-borrows/pure-functions.rs ... FAILED
      4 test [run-pass] pass/shared-borrows/static.rs ... FAILED
      4 test [run-pass] pass/with-spec/box-specification.rs ... FAILED
      4 test [run-pass] pass/with-spec/fields-spec.rs ... FAILED
      4 test [run-pass] pass/with-spec/identity-spec.rs ... FAILED
      4 test [run-pass] pass/with-spec/ownership1.rs ... FAILED
      5 test [compile-fail] fail/erdinm/generics-basic-3-1.rs ... FAILED
      5 test [compile-fail] fail/erdinm/generics-basic-3-2.rs ... FAILED
      5 test [compile-fail] fail/erdinm/generics-basic-3-3.rs ... FAILED
      5 test [compile-fail] fail/erdinm/generics-basic-3-4.rs ... FAILED
      5 test [compile-fail] fail/erdinm/generics-basic-3-5.rs ... FAILED
      5 test [compile-fail] fail/erdinm/generics-basic-3-6.rs ... FAILED
      5 test [compile-fail] fail/erdinm/generics-basic-4-1.rs ... FAILED
      5 test [compile-fail] fail/erdinm/generics-basic-4-2.rs ... FAILED
      5 test [compile-fail] fail/erdinm/invariants-pledges-2-2.rs ... FAILED
      5 test [compile-fail] fail/erdinm/invariants-pledges-3-1.rs ... FAILED
      5 test [compile-fail] fail/erdinm/invariants-typestates-basic-2-3.rs ... FAILED
      5 test [compile-fail] fail/erdinm/pledges-basic-1.rs ... FAILED
      5 test [compile-fail] fail/erdinm/typestates-basic-1-2.rs ... FAILED
      5 test [compile-fail] fail/erdinm/typestates-basic-1-3.rs ... FAILED
      5 test [compile-fail] fail/issues/issue-72.rs ... FAILED
      5 test [compile-fail] fail-overflow/crates/348_cgmath_point.rs ... FAILED
      5 test [compile-fail] fail/with-spec/trees-wrong.rs ... FAILED
      5 test [compile-fail] fail/with-spec/wrong-identity.rs ... FAILED
      5 test [run-pass] pass/no-annotations/enum-single-discr.rs ... FAILED
      5 test [run-pass] pass/no-annotations/reassignment.rs ... FAILED
      5 test [run-pass] pass-overflow/mul_add_assign.rs ... FAILED
      5 test [run-pass] pass-overflow/nll-rfc/message.rs ... FAILED
      5 test [run-pass] pass-overflow/rosetta/100_doors.rs ... FAILED
      5 test [run-pass] pass-overflow/rosetta/Knuth_shuffle.rs ... FAILED
      5 test [run-pass] pass/pure-fn/issue-27.rs ... FAILED
      6 test [compile-fail] fail/erdinm/assert-on-expiry.rs ... FAILED
      6 test [compile-fail] fail/erdinm/pledges-basic-2-1.rs ... FAILED
      6 test [compile-fail] fail/erdinm/pledges-basic-2-2.rs ... FAILED
      6 test [compile-fail] fail/erdinm/pledges-basic-2-3.rs ... FAILED
      6 test [compile-fail] fail/erdinm/pledges-basic-2-4.rs ... FAILED
      6 test [compile-fail] fail/erdinm/pledges-basic-2-5.rs ... FAILED
      6 test [compile-fail] fail/erdinm/pledges-basic-2-6.rs ... FAILED
      6 test [compile-fail] fail/nll-rfc/wrong-case1.rs ... FAILED
      6 test [compile-fail] fail/with-spec/no-precondition.rs ... FAILED
      6 test [compile-fail] fail/with-spec/wrong-method.rs ... FAILED
      6 test [run-pass] pass/erdinm/generics-basic-6.rs ... FAILED
      6 test [run-pass] pass/erdinm/traits-basic-norm-reqd-call-pre.rs ... FAILED
      6 test [run-pass] pass/issues/issue-144.rs ... FAILED
      6 test [run-pass] pass/issues/issue-145.rs ... FAILED
      6 test [run-pass] pass/issues/issue-47-replace-arg.rs ... FAILED
      6 test [run-pass] pass/magic-wands/wand-identity.rs ... FAILED
      6 test [run-pass] pass/moves/basic.rs ... FAILED
      6 test [run-pass] pass/mut-borrows/basic.rs ... FAILED
      6 test [run-pass] pass-overflow/rosetta/Knapsack_Problem.rs ... FAILED
      6 test [run-pass] pass-overflow/rosetta/Selection_sort_generic.rs ... FAILED
      6 test [run-pass] pass/with-spec/trusted.rs ... FAILED
      7 test [compile-fail] fail/crates/wrong-081-mio.rs ... FAILED
      7 test [compile-fail] fail/crates/wrong-122-same-file.rs ... FAILED
      7 test [compile-fail] fail/issues/issue-25-wrong.rs ... FAILED
      7 test [compile-fail] fail/magic-wands/wrong-wand-identity.rs ... FAILED
      7 test [compile-fail] fail/with-spec/ensures-false.rs ... FAILED
      7 test [run-pass] pass/crates/081-mio.rs ... FAILED
      7 test [run-pass] pass/erdinm/generics-basic-3.rs ... FAILED
      7 test [run-pass] pass/erdinm/generics-basic-4.rs ... FAILED
      7 test [run-pass] pass/erdinm/generics-basic-7.rs ... FAILED
      7 test [run-pass] pass/erdinm/generics-basic-8.rs ... FAILED
      7 test [run-pass] pass/erdinm/traits-basic-norm-prov-call-pre.rs ... FAILED
      7 test [run-pass] pass/initialization/variables.rs ... FAILED
      7 test [run-pass] pass/issues/issue-118.rs ... FAILED
      7 test [run-pass] pass/mut-borrows/ref-arg.rs ... FAILED
      7 test [run-pass] pass/no-annotations/assert-true.rs ... FAILED
      7 test [run-pass] pass/no-annotations/bitwise-bool.rs ... FAILED
      7 test [run-pass] pass/no-annotations/char-eq.rs ... FAILED
      7 test [run-pass] pass/no-annotations/operations.rs ... FAILED
      7 test [run-pass] pass/pure-fn/complex-fn.rs ... FAILED
      7 test [run-pass] pass/with-spec/if-expr.rs ... FAILED
      7 test [run-pass] pass/with-spec/method.rs ... FAILED
      7 test [run-pass] pass/with-spec/simple-spec.rs ... FAILED
      8 test [compile-fail] fail/issues/issue-73.rs ... FAILED
      8 test [compile-fail] fail/issues/issue-74.rs ... FAILED
      8 test [compile-fail] fail/pure-fn/wrong-quantifiers.rs ... FAILED
      8 test [run-pass] pass/expiring-loans/borrow-die-with-moves.rs ... FAILED
      8 test [run-pass] pass/issues/issue-25.rs ... FAILED
      8 test [run-pass] pass/issues/issue-47-extract.rs ... FAILED
      8 test [run-pass] pass/issues/issue-47-move-ref.rs ... FAILED
      8 test [run-pass] pass/issues/issue-47-replace-self.rs ... FAILED
      8 test [run-pass] pass/loop-invs/nested-loops-3.rs ... FAILED
      8 test [run-pass] pass/mut-borrows/drop-dag.rs ... FAILED
      8 test [run-pass] pass/no-annotations/debug-assert-true.rs ... FAILED
      8 test [run-pass] pass/no-annotations/diverging-call.rs ... FAILED
      8 test [run-pass] pass/no-annotations/field-types.rs ... FAILED
      8 test [run-pass] pass/no-annotations/modulo.rs ... FAILED
      8 test [run-pass] pass/no-annotations/simple-assert.rs ... FAILED
      8 test [run-pass] pass-overflow/rosetta/Binary_search.rs ... FAILED
      8 test [run-pass] pass/rosetta/no-spec/Function_definition.rs ... FAILED
      9 test [compile-fail] fail/nll-rfc/message.rs ... FAILED
      9 test [compile-fail] fail/pure-fn/integer_bounds.rs ... FAILED
      9 test [compile-fail] fail/with-spec/binary-search.rs ... FAILED
      9 test [run-pass] pass/erdinm/generics-basic-2.rs ... FAILED
      9 test [run-pass] pass/expiring-loans/borrow-die-with-if.rs ... FAILED
      9 test [run-pass] pass/fold-unfold/basic.rs ... FAILED
      9 test [run-pass] pass/issues/issue-44.rs ... FAILED
      9 test [run-pass] pass/issues/issue-47-extract-simpl.rs ... FAILED
      9 test [run-pass] pass/mut-borrows/drop.rs ... FAILED
      9 test [run-pass] pass/mut-borrows/generic-reborrows.rs ... FAILED
      9 test [run-pass] pass/mut-borrows/restore.rs ... FAILED
      9 test [run-pass] pass/mut-borrows/tuple.rs ... FAILED
      9 test [run-pass] pass/no-annotations/check-move.rs ... FAILED
      9 test [run-pass] pass/no-annotations/minus.rs ... FAILED
      9 test [run-pass] pass/shared-borrows/mut-borrows.rs ... FAILED
     10 test [run-pass] pass/erdinm/typestates-basic-1.rs ... FAILED
     10 test [run-pass] pass/expiring-loans/borrow-join.rs ... FAILED
     11 test [run-pass] pass/erdinm/generics-basic-5.rs ... FAILED
     11 test [run-pass] pass/erdinm/traits-basic-norm-prov-call-post.rs ... FAILED
     11 test [run-pass] pass/erdinm/traits-basic-norm-reqd-call-post.rs ... FAILED
     11 test [run-pass] pass/expiring-loans/simple-expire-borrows.rs ... FAILED
     11 test [run-pass] pass/pure-fn/simple-fn.rs ... FAILED
     12 test [run-pass] pass/enums/builtin.rs ... FAILED
     12 test [run-pass] pass/erdinm/pledges-basic-1.rs ... FAILED
     12 test [run-pass] pass/no-annotations/either.rs ... FAILED
     12 test [run-pass] pass/no-annotations/enum-build.rs ... FAILED
     12 test [run-pass] pass/no-annotations/multiple-branches.rs ... FAILED
     12 test [run-pass] pass/no-annotations/shared-ref.rs ... FAILED
     12 test [run-pass] pass/no-annotations/structs.rs ... FAILED
     12 test [run-pass] pass-overflow/rosetta/Langtons_ant.rs ... FAILED
     12 test [run-pass] pass/with-spec/unsigned_ints.rs ... FAILED
     13 test [run-pass] pass/issues/issue-47-trait.rs ... FAILED
     13 test [run-pass] pass/no-annotations/enum-no-move.rs ... FAILED
     13 test [run-pass] pass/no-annotations/singleton-enum.rs ... FAILED
     13 test [run-pass] pass/paper-examples/borrows_align.rs ... FAILED
     13 test [run-pass] pass/paper-examples/points.rs ... FAILED
     14 test [run-pass] pass/copy/generics.rs ... FAILED
     14 test [run-pass] pass/crates/122-same-file.rs ... FAILED
     14 test [run-pass] pass/erdinm/invariants-basic-6.rs ... FAILED
     14 test [run-pass] pass/expiring-loans/borrow_die.rs ... FAILED
     14 test [run-pass] pass/expiring-loans/borrow-die-with-magic.rs ... FAILED
     14 test [run-pass] pass-overflow/rosetta/Selection_sort.rs ... FAILED
     14 test [run-pass] pass/with-spec/match-expr.rs ... FAILED
     14 test [run-pass] pass/with-spec/match-expr-variants.rs ... FAILED
     15 test [run-pass] pass/crates/ansi-term-external-call.rs ... FAILED
     15 test [run-pass] pass/enums/basic.rs ... FAILED
     15 test [run-pass] pass/enums/name-clashes.rs ... FAILED
     15 test [run-pass] pass/erdinm/invariants-basic-1.rs ... FAILED
     15 test [run-pass] pass/erdinm/invariants-basic-4.rs ... FAILED
     15 test [run-pass] pass/expiring-loans/return_borrow.rs ... FAILED
     15 test [run-pass] pass/issues/issue-156.rs ... FAILED
     15 test [run-pass] pass/no-annotations/enums.rs ... FAILED
     15 test [run-pass] pass/pure-fn/Dijkstras_algorithm-simpl.rs ... FAILED
     15 test [run-pass] pass/rosetta/Knuth_shuffle.rs ... FAILED
     15 test [run-pass] pass/shared-borrows/basic.rs ... FAILED
     15 test [run-pass] pass/with-spec/trait.rs ... FAILED
     16 test [run-pass] pass/issues/issue-98.rs ... FAILED
     16 test [run-pass] pass/no-annotations/int-match.rs ... FAILED
     16 test [run-pass] pass/shared-borrows/functions.rs ... FAILED
     17 test [run-pass] pass/erdinm/invariants-basic-5.rs ... FAILED
     17 test [run-pass] pass/issues/issue-85.rs ... FAILED
     17 test [run-pass] pass/magic-wands/wand-identity2.rs ... FAILED
     17 test [run-pass] pass/magic-wands/wand-identity3.rs ... FAILED
     17 test [run-pass] pass/no-annotations/casts.rs ... FAILED
     17 test [run-pass] pass/no-annotations/type-param.rs ... FAILED
     18 test [run-pass] pass/shared-borrows/conditionals.rs ... FAILED
     19 test [run-pass] pass/crates/131-tokio-io.rs ... FAILED
     19 test [run-pass] pass/erdinm/invariants-basic-2.rs ... FAILED
     19 test [run-pass] pass/erdinm/invariants-typestates-basic-2.rs ... FAILED
     19 test [run-pass] pass/issues/issue-61.rs ... FAILED
     19 test [run-pass] pass/no-annotations/option.rs ... FAILED
     19 test [run-pass] pass/with-spec/ownership2.rs ... FAILED
     20 test [run-pass] pass/erdinm/invariants-typestates-basic-1.rs ... FAILED
     20 test [run-pass] pass/issues/issue-75.rs ... FAILED
     20 test [run-pass] pass/no-annotations/create-box.rs ... FAILED
     20 test [run-pass] pass/no-annotations/example6.rs ... FAILED
     21 test [run-pass] pass/erdinm/invariants-basic-3.rs ... FAILED
     21 test [run-pass] pass/expiring-loans/use_returned_borrow.rs ... FAILED
     21 test [run-pass] pass/loop-invs/simple-inv.rs ... FAILED
     21 test [run-pass] pass/mut-borrows/num-traits-mult.rs ... FAILED
     21 test [run-pass] pass/no-annotations/enum.rs ... FAILED
     21 test [run-pass] pass/no-annotations/nested-match-simple.rs ... FAILED
     21 test [run-pass] pass/no-annotations/timeout.rs ... FAILED
     21 test [run-pass] pass/no-annotations/void.rs ... FAILED
     21 test [run-pass] pass/paper-examples/ownership_align.rs ... FAILED
     22 test [run-pass] pass/erdinm/invariants-pledges-2.rs ... FAILED
     22 test [run-pass] pass/erdinm/invariants-pledges-3.rs ... FAILED
     22 test [run-pass] pass/loop-invs/simple-nested.rs ... FAILED
     22 test [run-pass] pass/no-annotations/assertions.rs ... FAILED
     22 test [run-pass] pass/no-annotations/enum-discr.rs ... FAILED
     22 test [run-pass] pass/no-annotations/tree-with-box.rs ... FAILED
     22 test [run-pass] pass/rosetta/Ackermann_function.rs ... FAILED
     22 test [run-pass] pass/rosetta/Knights_tour.rs ... FAILED
     23 test [run-pass] pass/crates/008-num-traits-pow.rs ... FAILED
     23 test [run-pass] pass/issues/issue-34.rs ... FAILED
     23 test [run-pass] pass/nll-rfc/message.rs ... FAILED
     23 test [run-pass] pass/no-annotations/Dijkstras_algorithm-simpl2.rs ... FAILED
     23 test [run-pass] pass/no-annotations/example3.rs ... FAILED
     23 test [run-pass] pass/no-annotations/nested-match.rs ... FAILED
     23 test [run-pass] pass/rosetta/no-spec/Mutual_recursion.rs ... FAILED
     23 test [run-pass] pass/shared-borrows/loops.rs ... FAILED
     24 test [run-pass] pass/erdinm/invariants-pledges-4.rs ... FAILED
     24 test [run-pass] pass/loop-invs/simple-loop.rs ... FAILED
     24 test [run-pass] pass/paper-examples/demo1.rs ... FAILED
     25 test [run-pass] pass/no-annotations/unreachable.rs ... FAILED
     26 test [run-pass] pass/loop-invs/if-loop.rs ... FAILED
     27 test [run-pass] pass/issues/issue-133.rs ... FAILED
     27 test [run-pass] pass/loop-invs/loop-fields.rs ... FAILED
     27 test [run-pass] pass/presentations/fib.rs ... FAILED
     27 test [run-pass] pass/pure-fn/recursive-pure-fn.rs ... FAILED
     28 test [run-pass] pass/loop-invs/fib.rs ... FAILED
     28 test [run-pass] pass/loop-invs/sum.rs ... FAILED
     29 test [run-pass] pass/nll-rfc/borrow_first.rs ... FAILED
     29 test [run-pass] pass/no-annotations/unit-type-field.rs ... FAILED
     29 test [run-pass] pass/pure-fn/generics.rs ... FAILED
     29 test [run-pass] pass/rosetta/no-spec/Factorial.rs ... FAILED
     30 test [run-pass] pass/erdinm/pledges-basic-2.rs ... FAILED
     31 test [run-pass] pass/expiring-loans/pure-fn-loan.rs ... FAILED
     31 test [run-pass] pass/issues/issue-134.rs ... FAILED
     31 test [run-pass] pass/mut-borrows/basic-reborrows.rs ... FAILED
     32 test [run-pass] pass/issues/issue-118-1.rs ... FAILED
     33 test [run-pass] pass/no-annotations/example2.rs ... FAILED
     34 test [run-pass] pass/issues/issue-187-1.rs ... FAILED
     37 test [run-pass] pass/loop-invs/nested-loops-2.rs ... FAILED
     37 test [run-pass] pass/loop-invs/sum-framing.rs ... FAILED
     39 test [run-pass] pass/expiring-loans/pure-fn-loan-2.rs ... FAILED
     41 test [run-pass] pass/no-annotations/list.rs ... FAILED
     42 test [run-pass] pass/shared-borrows/reborrowing.rs ... FAILED
     45 test [run-pass] pass/pure-fn/len-lookup.rs ... FAILED
     45 test [run-pass] pass/pure-fn/quantifiers.rs ... FAILED
     46 test [run-pass] pass/no-annotations/nice-example.rs ... FAILED
     47 test [run-pass] pass/issues/issue-39.rs ... FAILED
     48 test [run-pass] pass/rosetta/Heapsort.rs ... FAILED
     50 test [run-pass] pass/pure-fn/ref-mut-arg.rs ... FAILED
     55 test [run-pass] pass/paper-examples/force_increasing.rs ... FAILED
     56 test [run-pass] pass/larger/first-final.rs ... FAILED
     62 test [run-pass] pass-overflow/rosetta/Knights_tour_generic.rs ... FAILED
     63 test [run-pass] pass/nll-rfc/case1.rs ... FAILED
     63 test [run-pass] pass/paper-examples/routes.rs ... FAILED
     65 test [run-pass] pass/rosetta/Knapsack_Problem.rs ... FAILED
     68 test [run-pass] pass/mut-borrows/binary_search.rs ... FAILED
     79 test [run-pass] pass/rosetta/Fibonacci_sequence.rs ... FAILED
     99 test [run-pass] pass/with-spec/list.rs ... FAILED
```
</details>

**Comment by fpoli** [comment]
> Ah you found the branch ;) I forgot to add it to the PR, sorry.

I didn't, I was just guessing :)

**Comment by frececroka** [comment]
I moved some of the tests that fail often to the `quick/` folder. One thing that bothers me a bit is that the original folders are now missing the tests. Take `mut-borrows/binary_search.rs` for example. I moved this file to `quick/mut-borrows-binary-search.rs`. Someone looking into the `mut-borrows/` folder to see what test cases we have for mutable borrows will not immediately see that there is a binary search test case, because it is somewhere else. What do you think?

**Comment by fpoli** [comment]
To me this is perfectly fine, because we don't have a convention for the folders in `tests/verify/`. It's very common that a test uses multiple features, and in the end the only important thing is that the test remains *somewhere* in `tests/verify/`. So, the proper classification is useful but has a very low priority, while not running the *same* test multiple times is more useful.

@vakaras @cmatheja any thoughts?

**Comment by frececroka** [comment]
Okay, that makes sense. How many tests would you move to the `quick/` folder? Right now the quick tests take 4.5 minutes for 14 tests (excluding build time).

**Comment by vakaras** [comment]
> To me this is perfectly fine, because we don't have a convention for the folders in `tests/verify/`. It's very common that a test uses multiple features, and in the end the only important thing is that the test remains _somewhere_ in `tests/verify/`. So, the proper classification is useful but has a very low priority, while not running the _same_ test multiple times is more useful.
> 
> @vakaras @cmatheja any thoughts?

This is also fine with me.

**Comment by fpoli** [comment]
> Okay, that makes sense. How many tests would you move to the `quick/` folder? Right now the quick tests take 4.5 minutes for 14 tests (excluding build time).

Staying under 5 minutes with 14 tests sounds perfect. Is this ready for merge?

**Comment by frececroka** [comment]
It's ready. We can always add and remove tests to/from the quick folder in the future. But right now there should be enough in there to see if it proves useful.

**Pull request merged**
