### PR TITLE
Use `FxHashMap`/`FxHashSet` in `analysis`

### PR DESCRIPTION
**Pull request by teymour-aldridge**
(related to #711)

### CODE REVIEW

**Comment by teymour-aldridge** [comment]
oops, I think I forgot to update some dependents of this crate

**Review by vakaras — APPROVED** [review]
Looks great! Thanks!

**Comment by vakaras** [comment]
@teymour-aldridge Could you please rebase on `master`? I have just merged a compiler version update, which may cause your PR to fail CI. Thanks!

**Comment by teymour-aldridge** [comment]
Rebased!

**Comment by vakaras** [comment]
> Rebased!

Thanks!

**Comment by vakaras** [comment]
Thank you for fixing this!

**Pull request merged**
