### PR TITLE
Fix the script that dumps lifetime information

### PR DESCRIPTION
**Pull request by vakaras**
Replace the old `dump_borrowck_info.rs` with new code.

### CODE REVIEW

**Comment by Aurel300** [comment]
Does this fix any existing issues?

**Comment by vakaras** [comment]
> Does this fix any existing issues?

No. This is the code for visualising compiler's internal information.

**Comment by fpoli** [comment]
What's the way to run the script?

**Comment by vakaras** [comment]
> What's the way to run the script?

Same as before: `PRUSTI_DUMP_BORROWCK_INFO=true`.

**Pull request merged**
