### PR TITLE
Caching CI Builds

### PR DESCRIPTION
**Pull request by gavinleroy**
This PR was opened to address issue #665 regarding caching CI builds.

From material online, it seems to me that the [`Swatinemt/rust-cache`](https://github.com/marketplace/actions/rust-cache) action is frequently used for Rust projects and is the best option. I've used `rust-cache@v1.3.0` as it is a stable release, whereas `rust-cache@v1` points to the master branch. 

One potential problem I see here is that the [action job](https://github.com/marketplace/actions/rust-cache#cache-details) is part of the key. Currently, if a key is specified this is *in addition to* the automatic keys, however, in the future there may be an API option for overriding the key, in which case the GitHub Action job could be removed from the key. To my understanding, this means that between different jobs (e.g. building and testing) there will be a cache miss when theoretically they could use the same cached build. 

A few simple timings I gathered:

| OS          | Build Cache Miss | Build Cache Hit |
| ------------ | ----------------------- | --------------------- |
| Ubuntu    | 11m 19s               | 4m 13s              |
| Windows | 23m 48s               | 7m 11s              |
| Mac         | 17m 31s              | 5m 31s               |

### CODE REVIEW

**Comment by fpoli** [comment]
Nice! Thanks

**Comment by fpoli** [comment]
My only preference is to leave `.github/workflows/deploy.yml` without caching, just to have less moving parts in the build that releases Prusti. Since we use nightly `rustc`, it's possible to get weird bugs from time to time. The deploy workflow is not called when checking PRs, so it shouldn't be noticeable.

**Comment by gavinleroy** [comment]
Yes, I agree, caching the build in `deploy.yml` is indeed unnecessary.

I also just added caching to the `test-on-crates.yml` which is also run on pull requests.

**Comment by fpoli** [comment]
Great, thanks!

**Pull request merged**
