### PR TITLE
Upgrade Java bindings for Scala 2.13

### LINKED ISSUE #281: Flaky test mut-borrows-binary-search.rs
Test `verify/pass/quick/mut-borrows-binary-search.rs` is flaky and should be fixed or disabled.

See for example https://github.com/viperproject/prusti-dev/pull/279/checks?check_run_id=1460875146

### PR DESCRIPTION
**Pull request by fpoli**
@Aurel300 This should fix the build.

Closes #281.

### CODE REVIEW

**Comment by Aurel300** [comment]
I think Fábio mentioned some segfaults with Java 11 and recommended OpenJDK 15?

**Comment by fpoli** [comment]
> I think Fábio mentioned some segfaults with Java 11 and recommended OpenJDK 15?

Yes. I'm running with 11 just to see the error message at least once, to recognize it in future debugging sessions :)

**Comment by fpoli** [comment]
Also, I still have to find a nice way of installing OpenJDK 15 on Ubuntu 18.04 (the Github runner) and I have to find some time to upgrade from my Ubuntu 16.04 :disappointed:

**Comment by Aurel300** [comment]
FWIW I needed to do a clean build (`./x.py clean` before `./x.py build --all`), because I was getting errors about `-ljvm` not resolving.

Also, I just got this message when running a test:

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/r/prusti-dev/viper_tools/backends/silicon.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/r/prusti-dev/viper_tools/backends/ch.qos.logback.logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
```

Seems to just be informative but maybe something is wrong with how `silicon.jar` is packaged?

**Comment by vakaras** [comment]
> Also, I just got this message when running a test:
> 
> ```
> SLF4J: Class path contains multiple SLF4J bindings.
> SLF4J: Found binding in [jar:file:/r/prusti-dev/viper_tools/backends/silicon.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: Found binding in [jar:file:/r/prusti-dev/viper_tools/backends/ch.qos.logback.logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
> SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
> ```
> 
> Seems to just be informative but maybe something is wrong with how `silicon.jar` is packaged?

I think @aterga fixed this last time.

cc @fabiopakk

**Comment by fpoli** [comment]
> FWIW I needed to do a clean build (`./x.py clean` before `./x.py build --all`), because I was getting errors about `-ljvm` not resolving.
> 
> Also, I just got this message when running a test:
> 
> ```
> SLF4J: Class path contains multiple SLF4J bindings.
> SLF4J: Found binding in [jar:file:/r/prusti-dev/viper_tools/backends/silicon.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: Found binding in [jar:file:/r/prusti-dev/viper_tools/backends/ch.qos.logback.logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
> SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
> ```
> 
> Seems to just be informative but maybe something is wrong with how `silicon.jar` is packaged?

Indeed, it seems that there are duplicate classes. I already opened an issue at https://github.com/viperproject/viperserver/issues/26

**Pull request merged**
