### PR TITLE
Squash commits when merging.

### PR DESCRIPTION
**Pull request by vakaras**
Squash all commits when merging the PR.

@Aurel300 @fpoli @JonasAlaif Let me know if you have any concerns.

### CODE REVIEW

**Comment by fpoli** [comment]
Does this means that from now on all commits should be compiling, passing all tests, clippy and fmt? Even when manually merging?

**Comment by vakaras** [comment]
> Does this means that from now on all commits should be compiling, passing all tests, clippy and fmt? Even when manually merging?

No, it simply means that bors will squash the commits into one when merging the PR.

**Comment by JonasAlaif** [comment]
I would say so yeah (that this _should_ be what happens), one would have to select "Squash and merge" from the dropdown when merging manually

**Comment by Aurel300** [comment]
This makes it more difficult to bisect though…

**Comment by fpoli** [comment]
Should we move the decision to the next technical meeting?

**Comment by vakaras** [comment]
> This makes it more difficult to bisect though…

@JonasAlaif pointed out that this potentially would be the opposite because all commits would be the compiling ones.

**Pull request merged**
