### PR TITLE
Fix doc

### PR DESCRIPTION
**Pull request by pixelshot91**

### CODE REVIEW

**Comment by Aurel300** [comment]
Thanks! The changes look good, but why the new anchor? I don't see it used anywhere.

**Comment by pixelshot91** [comment]
The anchor is used here: https://viperproject.github.io/prusti-dev/user-guide/tour/pledges.html#writing-a-test-for-our-specification
Right now the snippet only shows this:
```rust
#[cfg(prusti)]
mod prusti_tests {
    use super::*;
```

**Comment by fpoli** [comment]
Can we merge, @Aurel300?

**Comment by Aurel300** [comment]
> The anchor is used here: [...]

Ah, my bad. Thanks!

**Pull request merged**
