### PR TITLE
Update rustc to nightly-2021-02-15

### PR DESCRIPTION
**Pull request by viper-admin**
* Update rustc to `nightly-2021-02-15`.

@Aurel300 could you take care of this?

### CODE REVIEW

**Comment by Aurel300** [comment]
@fpoli I think your new rotation script has some issues :) (But I will take care of this one.)

**Comment by fpoli** [comment]
> @fpoli I think your new rotation script has some issues :) (But I will take care of this one.)

Oops, I did an off-by-one in checking who's next. If it's fine for you I'll leave it as it is.

**Comment by Aurel300** [comment]
Panic macros have changed, which is fine, but it seems with https://github.com/rust-lang/rust/pull/80851 we might not be able to tell apart `panic!()` and `assert!(some_bool, "msg")`.

**Comment by Aurel300** [comment]
I'll merge this and fix the `panic!()`/`assert!(...)` problem once https://github.com/rust-lang/rust/issues/82157 is resolved.

**Pull request merged**
