### PR TITLE
Update dependencies (nightly-2022-01-13)

### PR DESCRIPTION
**Pull request by viper-admin**
* [x] Update rustc version to `nightly-2022-01-13`.
* [x] Manualy update outdated dependencies (see the list below).
* [x] Manualy run `cargo update`.

<details><summary>List of direct outdated dependencies:</summary>

```
$ cargo outdated --root-deps-only --workspace

info: syncing channel updates for 'nightly-2022-01-01-x86_64-unknown-linux-gnu'
info: latest update on 2022-01-01, rust version 1.59.0-nightly (cfa3fe5af 2021-12-31)
info: downloading component 'cargo'
info: downloading component 'llvm-tools-preview'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustc-dev'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'llvm-tools-preview'
info: installing component 'rust-std'
info: installing component 'rustc'
info: installing component 'rustc-dev'
info: installing component 'rustfmt'
    Updating git repository `https://github.com/rust-lang/cargo.git`
analysis
================
Name   Project  Compat  Latest   Kind    Platform
----   -------  ------  ------   ----    --------
serde  1.0.131  ---     1.0.132  Normal  ---
syn    1.0.82   ---     1.0.84   Normal  ---

prusti-common
================
Name   Project  Compat  Latest   Kind    Platform
----   -------  ------  ------   ----    --------
serde  1.0.131  ---     1.0.132  Normal  ---

viper
================
Name   Project  Compat  Latest   Kind    Platform
----   -------  ------  ------   ----    --------
serde  1.0.131  ---     1.0.132  Normal  ---

viper-sys
================
Name  Project  Compat  Latest  Kind   Platform
----  -------  ------  ------  ----   --------
ureq  2.3.1    ---     2.4.0   Build  ---

vir
================
Name         Project  Compat  Latest   Kind    Platform
----         -------  ------  ------   ----    --------
proc-macro2  1.0.34   ---     1.0.36   Normal  ---
quote        1.0.10   ---     1.0.14   Normal  ---
serde        1.0.131  ---     1.0.132  Normal  ---
syn          1.0.82   ---     1.0.84   Normal  ---

vir-gen
================
Name         Project  Compat  Latest  Kind    Platform
----         -------  ------  ------  ----    --------
proc-macro2  1.0.34   ---     1.0.36  Normal  ---
quote        1.0.10   ---     1.0.14  Normal  ---
syn          1.0.82   ---     1.0.84  Normal  ---

prusti-contracts-internal
================
Name         Project  Compat  Latest  Kind    Platform
----         -------  ------  ------  ----    --------
proc-macro2  1.0.34   ---     1.0.36  Normal  ---

prusti-specs
================
Name         Project  Compat  Latest   Kind    Platform
----         -------  ------  ------   ----    --------
proc-macro2  1.0.34   ---     1.0.36   Normal  ---
quote        1.0.10   ---     1.0.14   Normal  ---
serde        1.0.131  ---     1.0.132  Normal  ---
syn          1.0.82   ---     1.0.84   Normal  ---

prusti-interface
================
Name   Project  Compat  Latest   Kind    Platform
----   -------  ------  ------   ----    --------
serde  1.0.131  ---     1.0.132  Normal  ---

prusti-viper
================
Name   Project  Compat  Latest   Kind    Platform
----   -------  ------  ------   ----    --------
serde  1.0.131  ---     1.0.132  Normal  ---

prusti-server
================
Name      Project  Compat  Latest   Kind    Platform
----      -------  ------  ------   ----    --------
clap      2.34.0   ---     3.0.0    Normal  ---
num_cpus  1.13.0   ---     1.13.1   Normal  ---
reqwest   0.10.10  ---     0.11.8   Normal  ---
serde     1.0.131  ---     1.0.132  Normal  ---
tokio     0.2.25   ---     1.15.0   Normal  ---
warp      0.2.5    ---     0.3.2    Normal  ---

prusti-launch
================
Name   Project  Compat  Latest   Kind    Platform
----   -------  ------  ------   ----    --------
nix    0.23.0   ---     0.23.1   Normal  cfg(unix)
serde  1.0.131  ---     1.0.132  Normal  ---

test-crates
================
Name   Project  Compat  Latest   Kind    Platform
----   -------  ------  ------   ----    --------
serde  1.0.131  ---     1.0.132  Normal  ---

systest
================
Name  Project  Compat  Latest  Kind   Platform
----  -------  ------  ------  ----   --------
ureq  2.3.1    ---     2.4.0   Build  ---
```
</details>

@Aurel300 could you take care of this?

### CODE REVIEW

**Comment by Aurel300** [comment]
I've updated to `2022-01-13` since this got a bit stale. We can probably skip the next update which should happen in ~2 days?

@vakaras The clippy failures are coming from the generated VIR code (mostly). Do you know where to insert this `#[must_use]` attribute to fix them?

**Comment by vakaras** [comment]
> @vakaras The clippy failures are coming from the generated VIR code (mostly). Do you know where to insert this `#[must_use]` attribute to fix them?

Yes. I will push a commit that fixes them.

**Comment by Aurel300** [comment]
`merge.rs` failed on Mac, as @fpoli also [noticed](https://github.com/viperproject/prusti-dev/issues/819#issuecomment-1007410210). Should I disable it as flaky for now?

**Comment by vakaras** [comment]
> `merge.rs` failed on Mac, as @fpoli also [noticed](https://github.com/viperproject/prusti-dev/issues/819#issuecomment-1007410210). Should I disable it as flaky for now?

Sure. Just please make sure that there is an open issue to track that.

**Pull request merged**
