### PR TITLE
Fix #714 by constructing snapshots for enums

### LINKED ISSUE #714: Construct empty enum variants in pure code
The following program fails to verify, for a reason similar to issue #693:

```rust
use prusti_contracts::*;

#[derive(Clone, Copy)]
pub enum E {
    A,
    B,
    C
}

impl E {
    #[pure]
    pub fn len(&self) -> usize {
        0
    }
}

#[pure]
pub fn a() -> E {
    E::A
}

#[pure]
pub fn test() -> usize {
    a().len()
}

fn main() {}
```

Error:
```
error: [Prusti internal error] consistency error in test: Consistency error: Local variable _0 not found. (@0.0)
```

Code to be fixed: https://github.com/viperproject/prusti-dev/blob/0d5847141e430a4f31ad0f00366b335527a95b0f/prusti-viper/src/encoder/mir/pure_functions/interpreter.rs#L872-L880

Fix: Construct a snapshot even for enumeration variants that have no arguments.

### PR DESCRIPTION
**Pull request by fpoli**
* Fix #714 by constructing snapshots for enums
* Add `Encoder::encode_snapshot_constant(&self, expr: &mir::Constant<'tcx>) -> EncodingResult<vir::Expr>`.

### CODE REVIEW

**Comment by fpoli** [comment]
@vakaras I don't think this would conflict with https://github.com/viperproject/prusti-dev/pull/712. Do you have uncommitted changes?

**Review by vakaras — APPROVED** [review]
LGTM

**Comment by vakaras** [comment]
> @vakaras I don't think this would conflict with #712. Do you have uncommitted changes?

Yes, rebasing should not be a problem.

**Comment by fpoli** [comment]
I don't know exactly how, but PR #710 managed to add `tests/verify/pass/issues/issue-709.rs` even if `mir::Rvalue::Repeat` was unsupported :thinking:

**Pull request merged**
