### PR TITLE
Disallow spacing between Prusti operators

### PR DESCRIPTION
**Pull request by JonasAlaif**
Works with the changes here

### CODE REVIEW

**Comment by Aurel300** [comment]
What is this meant to fix? The test failure looks relevant.

There are some things wrong with the spacing parsing, in particular something like `>,` (the end of a generic argument list before a comma) might misparse, but I'm not sure this helps.

**Comment by vakaras** [comment]
@JonasAlaif This is the wrong approach. You need to actually get the span and check that the spans are next to each other.

**Comment by JonasAlaif** [comment]
Hmm it's strange that this fails though (when used with `quote!`), running it on actual code it seems to work.
Passing:
pass

Failing:
fail

**Comment by JonasAlaif** [comment]
@vakaras, @Aurel300 CI passes now, what do you think?

**Review by vakaras — COMMENTED** [review]
Looks good to me, but I am not an expert so would be good to get @Aurel300 feedback.

**Comment by Aurel300** [comment]
LGTM

bors r+

**Pull request merged**
