### PR TITLE
Add EncodedArrayTypes struct for result of encode_array_types

### PR DESCRIPTION
**Pull request by dario23**
The struct is local to procedure_encoder, just meant to not have to type
out very lengthy tuples.

### CODE REVIEW

**Comment by dario23** [comment]
hm, is something up with the quick-tests? fails with `fatal: couldn't find remote ref array-ty-struct`

**Comment by fpoli** [comment]
> hm, is something up with the quick-tests? fails with `fatal: couldn't find remote ref array-ty-struct`

Yes. Could you add `continue-on-error: true` after [this line](https://github.com/viperproject/prusti-dev/blob/53096dad43e9ce7c9c45d3f4b1c6b062b57534e5/.github/workflows/test.yml#L45) (same indentation as `run:`)?

**Comment by dario23** [comment]
> Yes. Could you add `continue-on-error: true` after [this line](https://github.com/viperproject/prusti-dev/blob/53096dad43e9ce7c9c45d3f4b1c6b062b57534e5/.github/workflows/test.yml#L45) (same indentation as `run:`)?

seems to have done the trick for quick-tests, yes. now just the windows-tests remaining :-)

should i leave this commit in, or do you want that to be a separate PR (not by me, necessarily)?

**Comment by fpoli** [comment]
> should i leave this commit in, or do you want that to be a separate PR (not by me, necessarily)?

The proper fix should be https://github.com/viperproject/prusti-dev/pull/500, but I cannot easily test it. After I merge that you could try to rebase on master and remove the `continue-on-error`.

**Comment by fpoli** [comment]
> seems to have done the trick for quick-tests, yes. now just the windows-tests remaining :-)

Oh, I thought I fixed that issue on windows :(

It's a bug in rustup: https://github.com/rust-lang/rustup/issues/2748

**Pull request merged**
